### ISSUE TITLE
ns.stanek.acceptGift() always returns false since v2.5.2

### ISSUE THREAD

**Issue by GDennis** [bitburner-official/bitburner-src#1000]
# ns.stanek.acceptGift() always returns false since v2.5.2

- [x] Save file
[bitburnerSave_1703893077_BN12x45 bug stanek acceptGift.json](https://github.com/bitburner-official/bitburner-src/files/13796515/bitburnerSave_1703893077_BN12x45.bug.stanek.acceptGift.json)
- [x] Minimal scripts to reproduce the issue
run enterStanek.js enter
- [x] Steps to reproduce
Call ns.stanek.acceptGift()
It always returns false since version 2.5.2.
- [x] Version of the game
Bitburner v2.5.2 (c6141f2ad)

**Comment by d0sboots** [comment]
I investigated this, and can confirm. I don't know enough about Stanek to know the proper fix, though.

The issue is that the condition was changed to check if `inviteReqs.isSatisfied` for CotMG, but that will never be the case because you don't get a traditional invitation, you have to go to the church.

**Comment by d0sboots** [comment]
@jjclark1982 for ideas
