### ISSUE TITLE
getAugmentationGraftTime returns incorrect value

### ISSUE THREAD

**Issue by fasmat** [bitburner-official/bitburner-src#1012]
I've been experimenting with grafting and I am working on a script that automates it for me.

It seems like `getAugmentationGraftTime` returns incorrect values. If I sleep for the value returned and then start a new graft it will result in the current graft being cancelled at 98 or 99 percent. There seems to also be no way to check if there is already a graft in progress via scripting which would be a way around the issue. I could probably fix this myself with access to the singularity API (that I haven't unlocked yet) but I feel like this should be possible without?

Alternatively would it make sense to have a promise that can be awaited for the graft to be finished? In case it shouldn't be too easy without access to singularity.

**Comment by cigarmemr** [comment]
Say T is the time returned by `getAugmentationGraftTime()`. In case you:
- have NOT installed the augment "Neuroreceptor Management Implant"
AND 
- are NOT focused on the grafting process (clicked "Do something else", or set `focus` to `false` in `graftAugmentation()`)

Then the actual time required for grafting will be amplified by about 25% (to 125%*T) , as the "speed of grafting" is reduced by 20% when the two forementioned conditions are met. This is usually why script-held grafting processes are frequently interrupted by each other.

With singularity, you can easily go through this by either:
LSUyMFRlc3QlMjB0aGUlMjBmb3JlbWVudGlvbmVkJTIwYXVnJTIwaXMlMjBpbnN0YWxsZWQuJTIwSWYlMjBzbyUyQyUyMHNsZWVwJTI4VCsxMDAwJTI5JTNCJTIwb3RoZXJ3aXNlJTIwc2xlZXAlMjhUKjEuMjUrMTAwMCUyOS4lMjBMZWF2ZSUyMGElMjAxMDAwbXMlMjBnYXAlMjB0byUyMHByZXZlbnQlMjBhY2NpZGVudGFsbHklMjBicmVha2luZyUyMHRoZSUyMHByb2Nlc3MlMjB0b28lMjBlYXJseS4lMEEtJTIwUGVyaW9kaWNhbGx5JTIwY2hlY2slMjB3aGF0JTIwdGhlJTIwcGxheWVyJTIwaXMlMjB3b3JraW5nJTIwb24uJTIwSWYlMjBpdCUyMGlzJTIwc3RpbGwlMjBhJTIwZ3JhZnRpbmclMjBwcm9jZXNzJTJDJTIwc2xlZXAlMjglMjklMjBzb21lJTIwYWRkaXRpb25hbCUyMHRpbWUlMjB1bnRpbCUyMHRoZSUyMHBsYXllciUyMGlzJTIwZnJlZSUyMG9mJTIwd29ya2luZy4=
(is there a way to mark as spoiler here?)

But yes, neither of these can be done without singularity API. To graft safely you can just `sleep(T*1.25+1000)`, or use an argument to manually control whether to `sleep()` an additional 25% of T.

**Comment by d0sboots** [comment]
This bug is a great example of why things like getting the list of currently installed augs should be possible without singularity.

**Comment by fasmat** [comment]
@cigarmemr that was one of the issues, but even if I start `graftAugmentation` with focus set to `false` (e.g. over night) I would still fail to graft any augments because they are canceled just before they are finished.

I now added a buffer of a few seconds and compensate for the 25% extra time when I do not focus on grafting. But without your input and checking the bitburner source code I probably wouldn't even have thought about that being the cause of the issue. The documentation for the `grafting` namespace also doesn't seem to mention that `getAugmentationGraftTime` doesn't consider installed augs and if the player focuses on the graft or not.

**Comment by cigarmemr** [comment]
Yes that's a bit absurd. In fact I have been confused by the same problem for some time, and finally figured out what's going on.
Generally speaking, the actual duration of any `await`ed function is NOT reliable. Due to the order of execution of codes from multiple scripts, in addition of many random factors that affects machine precision, there will be up to 1~100ms dithering on the actual `await`ed time.
In most cases this would not be a problem --- we may not even be aware of the minor milliseconds difference. However for some particular operation like repeatedly grafting in a loop, we should make sure the actual `await`ed time is always longer (at least not shorter) than expected to prevent stopping grafting prematurely.
The easiest way to get rid of this is to `await` a bit longer than required, i.e. add 1000ms to the duration.

Another thing comes from the augment "Neuroreceptor Management Implant". Yes almost every work our character do in the Overview panel receives the 20% penalty if not focused, unless the said augment is installed. This includes working for faction/company, training at university/gym, doing crime, creating programs and finally, grafting.
I will say for sure it is annoying, especially for those just started burning bit, but also an interesting design. The problem is that the penalty is a bit too implicit. It would be better to display a conspicuous warning on the "Do something else" button.
