### ISSUE TITLE
web version "too much recursion" internal error

### ISSUE THREAD

**Issue by Deuterated** [bitburner-official/bitburner-src#1054]
### Environment

* Error: InternalError: too much recursion
* Page: Hacknet
* Version: v2.3.2 (be426896)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
* Features: lang=en-US cookiesEnabled=true doNotTrack=unspecified indexedDb=true
* Source: https://danielyxie.github.io/bitburner/dist/vendor.bundle.js

I was not given a file name for my save file. I just kinda left it running for 4 days, then when I woke up this morning my save file was corrupted. I'm not particularly stressed out about it, but thought you ought to know

**Comment by Caldwell-74** [comment]
tthats a pretty old version the current stable branch is v2.5.2 (c6141f2ad)

**Comment by d0sboots** [comment]
I wonder if it's because they're playing on danielyxie... But I thought that was still getting updated...

**Comment by Snarling** [comment]
We stopped updating the danielyxie repo because every update I had to open a PR and then message hydro asking him to merge in the changes, since I can't merge on that repo.

When we stopped updating that one, he added in a terminal message that prints when the game is loaded: `Bitburner old version, see https://bitburner-official.github.io/ instead`
