### ISSUE TITLE
Can the game be playable with Python script

### ISSUE THREAD

**Issue by pranjal779** [bitburner-official/bitburner-src#1057]
I wanted to play the game with Python Code
if possible can the game be playable with Python
please

**Comment by LJNeon** [comment]
This game is only truly playable with javascript (or typescript through the use of an external editor). You might be able to do a tiny bit with WASM but almost everything would still need to be in javascript even then, because the `ns` object is necessary for almost everything and WASM can't access it.

**Comment by d0sboots** [comment]
Going to close this one as not planned. Given the way the game is structured (it's fundamentally a web game), supporting non-js languages is somewhere between "too much work" and impossible.

**Comment by pranjal779** [comment]
i cri

**Comment by pranjal779** [comment]
> Going to close this one as not planned. Given the way the game is structured (it's fundamentally a web game), supporting non-js languages is somewhere between "too much work" and impossible.

I Know a little Javasscript I do want to play this game
so I will have to get better at JavaScript
i wish if python was also a way to play this game.

thank you for taking out the time to message me

Best Regards,
Pranjal
