### ISSUE TITLE
OmniTek Reputation

### ISSUE THREAD

**Issue by kubleeka** [bitburner-official/bitburner-src#1067]
I'm running Bitburner v2.5.2, and was invited to the faction OmniTek Incorporated, which has a requirement of having 400k reputation with OmniTek. When I got the invite, I had just passed 300k reputation with them. Mousing over OmniTek Incorporated in the Factions menu shows that the 400k reputation requirement is checked off, even with my actual reputation too low. The job listing "Head of Software" at OmniTek itself, which also requires 400k reputation, did not show the 400k requirement as checked off at the time, but did some minutes later, despite reputation still being too low.

**Comment by Caldwell-74** [comment]
that you got the invite at 300k must be cause you backdoored their server 
this lowers the required from 400k to 300k

the other displays should show that or atleast give an hint that backdooring might reduce it in some way

**Comment by cigarmemr** [comment]
The reputation requirement for applying job promotion as well as joining their faction will be lower by 100k. This is more or less too implicit for sure.

I have an idea: Instead of lower the requirements, grant the player an instant 100k reputation to them after backdooring their server. This should make the reputation display more consistant.
