### ISSUE TITLE
DEV: "git blame" could be better for contributors

### ISSUE THREAD

**Issue by adeilt** [bitburner-official/bitburner-src#1091]
_Note: If you don't work on Bitburner itself, then this probably isn't relevant to you and can be safely ignored._

`git blame` - and vscode's Gitlens extension - currently show a lot of commits that could be ignored for the sake of blame.  In particular, there are multiple commits with the description "prettier" that are just reformatting done by the Prettier tool.  (The main one I keep seeing is [this commit](https://github.com/bitburner-official/bitburner-src/commit/a18bdd6afc77752bded2f0794bf35ad9d6455fa1).)

Adding these to a file (e.g. `.git_blame_ignore_revs`) tracked in the repository would allow contributors to ignore these commits for the purposes of blame with this command line:

```
git config --local blame.ignoreRevsFile .git_blame_ignore_revs
```

**Comment by d0sboots** [comment]
That's weird, I've searched through blame for a bunch of stuff and I've never noticed commits like that.

**Comment by Snarling** [comment]
The commit linked was a commit that actually first implemented a formatting requirement, so it ends up touching most of the code.

PRs for a while after that were being merged with all of their individual commits intact, so PRs that had a commit for doing lint/prettier would have those minor commits left intact.

New commits should almost never have separate commits for "prettier" once they get merged in, since PRs should now always be squashed into a single commit before merging. So git blame for anything recent should point to the overall PR where it was changed (and if it matters to you which commit within that PR made the change, you could check that PR to find out).

I'm not sure it makes sense to automatically ignore certain commits. Particularly when there are changes in indentation, old lines are not reliably mapped to their new counterparts 1:1, so I think ignoring these commits automatically may be inviting issues where the blame is done incorrectly. Whereas if the user has to look through the blame themselves, they can correct for any mismatched lines. Also, there is nothing guaranteeing that contributors have not added in any substantive changes during commits titled "prettier" - these commits are likely to just be formatting changes to satisfy the prettier requirements, but we don't have a guarantee of that.

I use the github web interface when looking through blame, but it's easy enough to just look for "blame before this commit" when I find a commit that technically changed the lines I am looking at but the change was not significant to what I'm looking for (whether it's a formatting change, renaming a variable, etc).


![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/f102a633-bd1f-46cf-969b-3d56aca3cbc2)

**Comment by d0sboots** [comment]
So, I'm kinda torn on this. On one hand, clearly neither me nor Snarling has ever felt the lack of this. Based on how my blame searches have gone (not just here but across *many* codebases), it's *never* as simple as just running `git blame`: Usually there's other changes to that line that aren't what you care about, or the whole thing was moved from another file, etc. Often you have to make some judgement calls and jump across multiple iterations of blame, sometimes doing some bisection, to find the proper line.

OTOH, I don't think adding this would *hurt* anything, and we aren't doing separate prettier commits anymore so it's not even like this file would be getting out of date. So I guess I tentatively lean towards "just commit it" for the folks who'd find it useful?

**Comment by d0sboots** [comment]
@Snarling Let's make a decision on this one way or another instead of leaving it hanging.

**Comment by adeilt** [comment]
I'm still learning my way around vscode and its ecosystem.

After poking around VSCode (with GitLens) more this morning I finally found this setup's version of "blame before this commit".  It's a little awkward to use, but it is there, and I don't find myself using blame so often that the awkwardness would scale up into a significant waste of time.

I've added a couple of sections to the bottom of #1092's description summarizing the arguments for or against in context of the discussion here.

**Comment by adeilt** [comment]
I should also add that I don't have any strong personal feeling that this should be "fixed" centrally.  I spent some time creating the list of commits for me to use and it seemed reasonable to offer to share, but I'll still have it even if nobody else finds it useful.

**Comment by Snarling** [comment]
I think it probably doesn't belong in the main repo, but really the only reason I didn't just merge it anyway was the inclusion of it directly on contributing.md as if setting up custom blame ignoring should be part of the normal contributing process.

If it's too cumbersome to use this with our repo while maintaining it from your own repo, I'm fine with merging it, but I don't think it needs to be highlighted in the contributing doc. It can just have a comment within itself saying how it can be used.

**Comment by adeilt** [comment]
You make a good point about it not being a normal part of the contributing process and I've reverted my changes to `CONTRIBUTING.md`.  I've also slightly expanded the documenting comments in `.git_blame_ignore_revs` to compensate.
