### ISSUE TITLE
Corporations when 'Use same sell amount for all cities' is deactivated still applies product price across all cities

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#113]
[Kaostico]
Steps to reproduce the issue

1. Create a product, e.g "Product A"
2. Once complete, set sell price for Product A in one city with "Use same sell amount for all cities" deactivated
3. Check other cities, sell price settings will have applied there also
4. Version of the game: Bitburner v2.1.0 (8f4636cb)

Expected behavior:
When "Use same sell amount for all cities" is deactivated, the prices shouldn't be shared between cities.

**Comments From Original Issue**

[chriswebb]
> Also had the same issue using v2.0.2

**Comment by G4mingJon4s** [comment]
The sell price is stored as one single value for all cities, as the MP of a product is the same for all cities. The sell amount however needs to be stored for each city, as one city could produce more than the other.
It just doesn't make sense to allow different prices for cities.
That's why the label of the switch explicitly says Sell amount and doesn't refer to both the sell amount and the sell price.

**Comment by Snarling** [comment]
Closing per comment above. May be reworked in the future to allow different sell prices in different cities, but for now this is not available.
