### ISSUE TITLE
Corporation dividends payout wrong?

### ISSUE THREAD

**Issue by NoOneNeedsThat** [bitburner-official/bitburner-src#1160]
the dividend payout between corp earnings and and final payout has a massive gap.
see screenshot

![BB_corp_dividends](https://github.com/bitburner-official/bitburner-src/assets/163121384/f129ad5a-91ed-4cf5-a377-703912a8b433)

as u can see, the corp is making 1.7 t profits/s
payout at 100% dividends is 70 b/s

I do understand taxes, but THIS much?
pleasy clarify, do you really calculate with like 99.95% taxes?!?

did i miss something?
 i cant imagine i am the first one to complain about this

**Comment by catloversg** [comment]
@NoOneNeedsThat It's much easier to see why it is like that if you provide the save file.
Make sure that you understand how dividend and tax work in this game: https://github.com/bitburner-official/bitburner-src/blob/dev/src/Documentation/doc/advanced/corporation/financial-statement.md

**Comment by NoOneNeedsThat** [comment]
thx for provided link...

still somehow wrong, imo, or i just dont get your idea:

edit: nevermind the part with the retained earnings, this one i did read wrong :-)
---according to the formulas provided in chapter "dividend", i would get 0 earnings if i set 100 percent dividends
(as in:  retained earnings = **(1 - 1)** * (hwatever profit my corp makes) * 10 = **0** * x * 10 = **0** , as my Math teacher told me, anyting multiplied with 0 is 0)---

also, the dividend formula should be " * 1-DividendTax ", not " ^ 1-DividendTax ", because otherwise i get like 2 mill dividends out of 12 mill corp profit (revenue- expenses), which, in fact, would mean like 80% taxes (and what, lawyer/consultant fees)?!?

imo, if i want to payout 100% of my profits, i should get 100% of my profits (minus taxes, of course), otherwise the money just disappears?!?

i mean, i totally understand that we all want to tax the super rich into oblivion, but atleast i need a solid explanation :-)

however, i added my savefile for checkup. corp is set up for some testing

[bitburnerSave_1710342305_BN2x2.json](https://github.com/bitburner-official/bitburner-src/files/14589696/bitburnerSave_1710342305_BN2x2.json)

**Comment by catloversg** [comment]
I'll give you an example. Let's check this screenshot (it's your save file).
![screenshot](https://github.com/bitburner-official/bitburner-src/assets/152669316/68fd2cf8-6690-4386-a8fa-6ea114ce7b6f)
(Screenshot is a bit dim because I take it when I'm in debug mode)
- Profit: 1.960t/s. The exact value is `1.9596552677560957e12`. Profit is `Revenue - Expenses`. $Revenue - Expenses=1.9596552677560957e12$.
- Dividend Percentage: 100. This means we convert 100% of profit to our personal money. $DividendRate=1$.
- $OwnedShares=TotalShares=12.69e9$
- You are in BN2, so $CorporationSoftcap=0.9$. You bought both `ShadyAccounting` and `GovernmentPartnership`. $DividendTax=1-0.9+0.15-0.05-0.1=0.1$.

Plug them into the formulas:
- $TotalDividends=1\ast1.9596552677560957e12\ast10=19.596552677560957e12$
- $Dividend = \left(12.69e9\ast\frac{19.596552677560957e12}{12.69e9}\right)^{1 - 0.1}=918.2516372061133e9$. This dividend is per cycle (10 seconds), so your dividend is `91.82516372061133e9` per second.

As you can see, there is nothing wrong here.
You need to understand that this is a game, and it has its own mechanisms. When the tax is `0.1`, the dividend is ${ExpectedDividend}^{0.9}$. It's NOT ${ExpectedDividend}\ast{0.9}$. There are many reasons why the formula(s) are like that, but most people don't care about them. They are only relevant if you want to balance the game mechanisms.

**Comment by d0sboots** [comment]
Thanks for giving a thorough explanation here. I'm going to close this, as there is no bug.

**Comment by NoOneNeedsThat** [comment]
@catloversg 
i do understand game mechanics, and if we go straight with the formulas, everythings fine

however, still bonkers imo. an example:
if we take all the numbers given above:
100% corp payout, 100% shares ownership, corp softcap 0.9  + shady acc + gov partner, 
but imagine a corp profit of 1$
we get a payout of 0.79$, which means 21% tax, and not the promised 10%
![grafik](https://github.com/bitburner-official/bitburner-src/assets/163121384/81cc1dff-3212-4ce9-8d8b-2cd6de7a56f1)

and we are talking about buying corp unlocks worth several t$

if we drop the shady acc + gov partner, its a solid 43% tax for a single $ (and not the promised 25% for BN2)
![grafik](https://github.com/bitburner-official/bitburner-src/assets/163121384/d099ad1b-f7ef-4a80-bea5-96b4688d21ff)

you can imagine the drop if you consider a tougher corp softcap like 0.7 or 0.5. that is what i try to say. of course, according to the formulas, everything is alright, but if you try to bring some common sense into it, it gets bonkers. 

unfortunately, i dont have a solid suggestion how to imrove this.
i still believe that there should be a change at the ^1-x , maybe something related with the corp income or corp valuation. also, up into the higher earnings the formula starts to make sense as you want to tax higher incomes with higher %, but for the beginning, its pretty hard. especially if you keep the cost for corp upgrades, divisions and office/warehouse prices in consideration. sure, once the corp ist running decent, it starts snowballing like crazy (yes, i had something like 1.0e^80 / s income in an earlier run, which could be nerfed imo), but especially at the beginning the only way to push the corp is hacknet hashes (as there is no way to bring personal cash into corp) and issuing new shares (with a delay timer). 
I also have to say that i didnt looked into the high tier BNs til now, so i also cant say anything about balancing there.

on the other hand, 1$/s would mean a yearly income of 31 536 000$, which could earn a 40% tax rate :-) . and also, once the corp ist running, its fun to play around. but as income source theres currently a way to high cash loss.

**Comment by catloversg** [comment]
The problem here is the discrepancy between the real world's concept and the game's mechanism. "Tax" in the game is not the same thing as "Tax" in the real world. When the tax is 10% in this game, there is nothing like "the promised 10%", it's just "0.1 is the number which will be used in the formula(s)". If it does not make sense, you can replace the word "Tax" with something else in your mind, e.g., "Business's special cost factor". Generally, we try to make the mechanism as reasonable as possible, but "suspension of disbelief" is required in some cases.

About the formula, the exponential function is a very popular function in this game because it "controls" the growth of everything. For example, the upgrade's cost function is also an exponential function.

Corporation has always been a special feature in this game. Its power is unmatchable, and that power comes with ridiculously complex mechanisms. Many parts of Corporation are unintuitive. I know that, so I understand your confusion. I hope that this does not sound like I want to dismiss your opinion. On the contrary, I welcome all suggestions, as long as they have specific details and are in proper context.

If you want to make more suggestions, you should come to our Discord server. It's much easier to discuss the details there.
