### ISSUE TITLE
IPvGO 5x5 two handicap is extreme

### ISSUE THREAD

**Issue by ghost** [bitburner-official/bitburner-src#1169]
Hello,

In the IPvGo Subnet Illuminati/w0r1d_d43m0n 5x5 board, the handicap is 2. This is too high for reasonable play (this is coming from a ~6k go player).

**Background**
On a 5x5 board, the winners are highly constrained under optimal play, see https://www.researchgate.net/publication/2925531_Solving_Go_On_Small_Boards 

With no handicap, black will always win if they play optimally and start at the center, gaining control of the entire board. If black plays at C2, optimally black will win by 3 points in traditional scoring (not quite the same as the game). Any other position, B2 and the edges, white can win under optimal conditions.

** Problem Statement **
The inclusion of two handicap stones most likely makes it impossible for the non-handicapped player to win under optimal conditions. I recognize that the algorithms used are not optimal conditions, but it makes it really stringent/you need to understand how the algorithms mess up, rather than understanding how the game of Go works.  

Under current setup, to win, you practically have to kill the other group. The board size is 25, the komi is 7.5 (or 9.5) (https://github.com/bitburner-official/bitburner-src/blob/edf8e24046cf07fdffd4d74242a1f88ab919387c/src/Go/Constants.ts#L53), meaning the total number of points is 32.5 (or 34.5). The minimum survivable group size is 8. This means that if white has a group larger than (or equal to) the corner life, white will win.  

** Suggestion for change **
I would suggest changing for the board size of 5 to have a handicap of 1 instead of 2. This could be done by explicitly limiting the maximum handicap size of the 5x5 board to 1.  
https://github.com/bitburner-official/bitburner-src/blob/edf8e24046cf07fdffd4d74242a1f88ab919387c/src/Go/boardState/boardState.ts#L63

If this makes it **too** easy, I would suggest pinning the handicap of the 5x5 board at the center of the board, as that is the optimal position. This change would be in the same file and fairly easy to make as the board and the number of handicaps are already in the function call. I wouldn't be opposed to fixing the position of the handicaps on other boards because that is the standard practice for 9x9 (c3 and center) and 13x13 boards (d4 and center). 
https://github.com/bitburner-official/bitburner-src/blob/edf8e24046cf07fdffd4d74242a1f88ab919387c/src/Go/boardState/boardState.ts#L116

I wouldn't suggest changing the komi, because that would involve more code changes/displace the changes to multiple locations in the code base. 

Thanks, 
MR herb
https://online-go.com/player/558487/

**Comment by d0sboots** [comment]
I agree that the 2 stone handicap is excessively harsh and should be changed.

However, a subtle but important aspect to ipvgo is recognizing how it is *not* regular go: The unusual board shapes change things up, and the fact of the matter is that you are *not* dealing with optimal play, but rather exploiting a suboptimal opponent.

**Comment by ficocelliguy** [comment]
@herbhouse @d0sboots The handicap of 2 on a 5x5 board is intentionally overtuned, intended as something of a challenge.  Since the large boards reward more base score (by being larger), have better multipliers, and the AI is worse at playing on large boards, the small boards are really just for fun. I was hoping it would give more opportunities to use the unusual cheat API methods, or creative script solutions in a limited space.

That being said, if it is essentially unplayable as-is, or is only an exercise in exploiting the AI in a way that is not fun, it definitely can be changed. The komi display and calculation all comes from a single lookup method, and can have custom rules for 5x5. Or, the handicap could be reduced (or moved to only have stones somewhere suboptimal, like on the edge of the board).

**Comment by ghost** [comment]
The small boards are actually really important for folks who are learning the game from scratch. I usually teach on a 7x7 for brand new players. 5x5 is a little too small for humans, but is great for testing out how automated systems work with endgame content. 

After reviewing the code for the AI, I was able to think of strategies to beat the AI under specific handicap configurations (B2 and B3 was the most reliable one, while some of the other ones were more dependent on random choice moves). But those strategies employed playing moves that a human would ignore, while the AI doesn't 'know' how to ignore them. 

On location of handicap: The current AI can't determine dead edge shapes that well, so it will constantly extend along the edges, till an extension doesn't result in a gain of liberties, so placing a handicap on the edge promotes this type of behavior. I would not suggest moving the handicap to any location because of this.

If we place a single stone in the center of the board, we're doing two things at once: 1. we're demonstrating to the user how impactful the first move is on a board, 'explaining' why a komi exists in a indirect way, 2. we are making it feasible for a mediocre player to play the 5x5 and think about what is happening on the board.  

The real question is who is the audience for this feature. Is it someone who is a 8k in Go, who can deduce how the AI is playing and make it make dumb moves, the coder who can look at the current code and improve it a little bit and iterate on losses/wins, or the person who is playing it live who perhaps learned go through playing the other AIs on bitburner or other online source but hasn't dedicated time to it.

**Comment by ficocelliguy** [comment]
The suggestion to make the handicap on the 5x5 board a single router always in the center seems like a good one. I like, as you mentioned, that it highlights the value of starting by playing tengen, and the advantage of first move.

In regards to the intended audience: My goal was to make a programming problem that had some very simple naïve solutions (such as the starter scripts given in https://github.com/bitburner-official/bitburner-src/blob/dev/src/Documentation/doc/programming/go_algorithms.md )  but also had nearly infinite depth to iteratively improve. The fact that the game is fun to play manually is as much as anything a side effect of the UI design: approachable tools for the player understand how to find some of these iterative improvements and to get hands-on with some heuristics. 

I learned Go from zero knowledge in the course of creating the feature in the last 6 months or so, so I really can't say confidently what good content for experienced Go players is :)

**Comment by d0sboots** [comment]
I'll add some Go-related comments here for stuff that might not be as obvious when you're totally self-taught.

1-stone handicaps aren't usually a thing, because this just means "white is going first instead of black." Usually, this is instead done as a reversed komi, which is mechanically the same thing but more "pure." However, for the purposes of IPvGO, where the player is always black, it makes more sense to implement it non-traditionally as a 1-stone handicap.

> The real question is who is the audience for this feature. Is it someone who is a 8k in Go, who can deduce how the AI is playing and make it make dumb moves, the coder who can look at the current code and improve it a little bit and iterate on losses/wins, or the person who is playing it live who perhaps learned go through playing the other AIs on bitburner or other online source but hasn't dedicated time to it.

I think the answer is "all of the above," although maybe weighted a little less towards experienced Go players, because there will be fewer of them. Because of that, I actually don't think always playing tengen is the best way forward, despite it being the best move to choose. This is because it remove a *huge* element of unpredictability from the play; if the first move is always tengen then a simple winning strategy can be scripted out of a few if statements.

Edit: This is not something that you would necessarily think of from a Go-playing perspective; your opponent is normally free to choose any move, including the best ones. But in IPvGO, we are facing a fixed algorithmic opponent, and we can know that it will always react a certain way given certain inputs. This doesn't require understanding the code; you can gain this knowledge just by playing several games against it.
