### ISSUE TITLE
bladeburner.getActionTime doesn't handle type = 'Idle'

### ISSUE THREAD

**Issue by mctylr-gh** [bitburner-official/bitburner-src#1214]
## ns.bladeburner.getActionTime(type, name)

`version.js: Version: 2.6.1dev Commit: ed59f325e Platform: Browser`

Code to reproduce:

```
    /** @param {NS} ns */
    export async function main(ns) {
	/* const jackson = ns.bladeburner.getCurrentAction(); */
	const jackson = {name: 'Idle', type: 'Idle'};
	const result = ns.bladeburner.getActionTime(jackson.type, jackson.name);
    }
```

Runtime Error message:

```
RUNTIME ERROR
blade-test.js@home (PID - 105352)

bladeburner.getActionTime: Invalid action type='Idle', name='Idle'

Stack:
blade-test.js:L5@Module.main
```

_May_ have occurred during #1154 or #1200. This is unconfirmed.

**Comment by Snarling** [comment]
Yeah that's my bad, Idle internally is not a real action type anymore, I didn't think it had any impact to the player-facing API.

What is the expected action time for "Idle"? Infinity?

**Comment by mctylr-gh** [comment]
Well, both `Infinity` since it can continue to be `Idle` indefinitely, but also `0` since it is available to switch to another action at any time with no penalty.

I suspect zero might break less code, but I wouldn't bet on it. To me, as long as it had a known value, I could live with it.

**Comment by Snarling** [comment]
See #1248 and #1249 

The way this was addressed on dev is through an API break communicated to the player.
ns.bladeburner.getCurrentAction now returns `null` when the player isn't performing an action, which then requires the player to conditionally deal with the null case before accessing any properties of the action.

The fake idle action that was previously returned was a trap - only 3 of the action-related functions accepted idle, and they all returned garbage data when called with idle. 4 other action-related functions already produced an error when called with idle.

Now, calling these functions with idle isn't really a valid concept, because idle no longer has a type and name, and the functions require string inputs for type and name.
