### ISSUE TITLE
Opponent's Go AI can lock up the game

### ISSUE THREAD

**Issue by kishitoku** [bitburner-official/bitburner-src#1228]
It seems like there is a possible lockup when executing `await ns.go.makeMove(x, y)`. I have a script linked that triggers it, but only very infrequently, and I have logs to prove that `go.makeMove()` is executing when it happens.

The logging code looks like
`ns.write("goLog.txt","Ready to make move at "+Date.now()+"\n","a")`
`let rvar = await ns.go.makeMove(x, y)`
`ns.write("goLog.txt","Opponent finished move at "+Date.now()+"\n","a")`
and the end of the error logs after the crash looks like
`Ready to make move at 1713804655468`
`Opponent finished move at 1713804656777`
`Ready to make move at 1713804656805`
` `
indicating the command never finished.

---Version ---
Bitburner v2.6.1dev (6beb6e9f9)

--- Save file ---
[bitburnerSave_1713805003_BN4x1.json.gz](https://github.com/bitburner-official/bitburner-src/files/15066262/bitburnerSave_1713805003_BN4x1.json.gz)

--- Scripts involved ---
[bugGo.txt](https://github.com/bitburner-official/bitburner-src/files/15066267/bugGo.txt)

--- Steps to reproduce ---
- Launch included script
- Await while the game iterates through Go games
- Eventually, the game will freeze and become unresponsive as though an infinite loop was entered. 

--- Additional info ---
This can take minutes or even hours of running the script to happen, so I believe it is dependent on the board state. Because of that I don't have a simpler script that can reproduce this yet.

When you reload the game after killing all scripts, you can actually see the AI freshly place the stalled piece on the board when you go to view the ipvgo tab.

Here are screenshots of the board state upon reloading and killing scripts, showing the move the AI never made.
![go1](https://github.com/bitburner-official/bitburner-src/assets/74622599/6e1c3936-f52d-4c2d-baf7-b62c2f75b182)
![go2](https://github.com/bitburner-official/bitburner-src/assets/74622599/d1f78df8-7be7-4277-b10c-2901705774db)

I am still collecting more information on opponent and board-states that accompany this freeze.

**Comment by ficocelliguy** [comment]
This could be a memory leak in the game, or in the player script provided. 

It could also be a looping condition in either. However, there is exactly one while loop in the entirety of the Go codebase, and it is not a super complicated one (adding new points it finds to an array to find a connected group) so I don't currently see how a closed loop could be happening there.

(Note that the AI placing a piece upon refreshing after the freeze and loading the board screen is a feature intended for playing manually, and is unrelated to the problem)

**Comment by kishitoku** [comment]
Any tips for further investigating if it might be a memory leak issue?

I don't think it can be an infinite loop in the script provided due to the nature of the debug logging.

**Comment by ficocelliguy** [comment]
I'm looking into this a bit now. @kishitoku were you on the IPvGO subnet page looking at the gameboard, or were you on the terminal/map/somewhere else when this happens? 

Were you on the browser or on electron/desktop?

**Comment by kishitoku** [comment]
I was on the terminal most times; never on the IPvGO page. I use the desktop client provided by Steam.

**Comment by d0sboots** [comment]
So.... appending to a file forever is in and of itself a memory leak XD

It's not like there's an actual filesystem here... all the "files" are just objects in memory. When you keep adding to them, they keep getting bigger. Logging with `print` or `tprint` doesn't have this issue because the oldest lines go away (they have a fixed scrollback size).

I'm not *sure* that's your issue, but it's something I'd definitely consider.

Aside from that, you can use the debug tools to get memory profiles and see what is taking up space, or what is causing heap growth over time.

**Comment by ficocelliguy** [comment]
I've been running this script in chrome, staring at the IPvGO subnet page for about ten hours, and the memory usage has not changed at all. The performance has not visibly changed, either. Nor have I hit any lockups or freezes. 

Also, thinking about the original reported issue: because the game doesn't hang when the same boardstate was loaded later from the original issue, the problem isn't the internal analytics tools / rendering / state representation etc (otherwise it would hang again on reload)

**Comment by kishitoku** [comment]
Since I hopped a couple bitnodes I've been having trouble reproducing the issue as well. I did gather confirmation from the script author about this being a shared issue before I submitted, and this is what he last said in discord

> I'm heading out of town in a few minutes for a few days.  I'll try to give them some info when I get back.  I do know that my script has certain "pauses" when run in super speedy mode.  I'll try to track down board state for those moments.

So for now I'm just keeping an eye on if I can get the game to start freezing up again, and if not, I guess waiting until I can get the info from the author himself.

**Comment by Sphyxis** [comment]
The version of the game that I have in Dev right now has 1 await sleep(0) in the game for the opponent getting and doing a move.  I currently experience what you would call Jitter/lockups at random times.  This is around .75 - 1.2 seconds of delay between moves when normally it's less than 10ms.  I believe it's due to certain move lookups locking things up.  I'll be testing tomorrow or the day after (I need to unpack) by removing various moves from the equation and seeing what stops the lockups.  Once I test all the moves I'll let you know the results.
@ficocelliguy @kishitoku

**Comment by Sphyxis** [comment]
I've done some testing, and the slowdowns happen more frequently on larger boards.  Further testing shows that my script jumps in time when pulling moves from the bottom of the list.  Over 1.1 seconds for my move compared to 0.07 seconds for the computer.  This shouldn't be very noticeable from a user using a normal build though.  I'll revamp my scripts to help reduce this lag.  My moves are comparable in time if not usually faster.  I have noticed that the skips appear more often when the opponent passes their turn.  I've also notice a large increase in time when you are looking directly at the board and about a another increase when looking at Status.  Perhaps an option to turn off certain animation effects would help?
More testing later.

**Comment by Sphyxis** [comment]
@ficocelliguy @kishitoku 
I've done tons of fights, 10,000+.  I've noticed no real stall like I do in Dev at times.  I'm guessing this is because I've stripped out all the sleeps but 1.
Suggestion:  Remove all but 1 sleep.  Keep the time consistent.  I'm guessing that there's an area with a large sleep that gets looped several times, creating a large amount of lag between moves and looking like it's stalling.

**Comment by ficocelliguy** [comment]
@Sphyxis are you suggesting pulling out the sleep() calls in the AI game code? I placed them as it is currently because, without them, there is a noticeable hiccup/stutter in the animations when playing on the board manually. The AI takes some time to decide on a move, and doing all of the processing at once blocks the UI for a moment in a very visible way, even on my fairly powerful PC.

**Comment by Sphyxis** [comment]
@ficocelliguy 
More a rearranging of them.  I've noticed without sleeps that the AI moves can take upwards of 300ms on my system.  Perhaps take note of the start time, put more minor sleeps between key areas to allow for updates, and at the end see how much time has passed and sleep to a standard time.
This will allow for you to even add augments to speed up the game (reduce that standard time), or set that time differently for different AI's, or to abort a move (pass) if it's taking too long.
Upwards of 600ms if you are viewing the board itself

**Comment by d0sboots** [comment]
You can return control to the browser with `sleep(0)`, there is no need to sleep for a positive amount of time (that might grow without bound).

Of course, the most correct way of dealing with long-running/compute-intensive tasks is to hoist them into a Web Worker.

**Comment by ficocelliguy** [comment]
This should be addressed with #1327 and #1345
