### ISSUE TITLE
Slash minigame timing off - development

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#124]
[steveturri]
When infiltrating, the slash minigame seems to have broken a bit.  In order to get success I need to click in preparing mode and not in attack mode.  

Development branch

**Comment by Snarling** [comment]
@steveturri tagging you, since it's a copied issue you won't get pinged otherwise. The change to slashgame was intentionally added by another contributor.

The logic was, when the guard goes from "guarding" to "preparing?", his guard has went down, which is when the game says to strike. With these three steps being present, waiting all the way until the guard is already attacking you didn't actually make sense.

Preparing had originally been added as a kind of difficulty equalizer for people who struggle with reaction time, but the associated SoA augment takes the place of that now. Now preparing is just the phase where you're supposed to attack.

**Comment by koenenalexander** [comment]
It might be i just need to get good, but i'm unable to successfully complete this mini-game even with the SoA augment. The transition from preparing to attacking is too fast for me and the SoA augment seems to be tied to when the attack phase starts instead of the preparing phase.

Also, the documentation still indicates you need to attack during the attack phase.
https://bitburner.readthedocs.io/en/latest/basicgameplay/infiltration.html

Edit: i checked my reaction time using https://humanbenchmark.com/tests/reactiontime and consistently got between 350-400ms, which is worse than the 270ms human average.

**Comment by Mughur** [comment]
The ReadTheDocs you linked is the old docs, we created a new one for various reasons.

https://bitburner-official.readthedocs.io/en/latest/basicgameplay/infiltration.html
There the slashing game's info is up to date

**Comment by Mughur** [comment]
@koenenalexander  The ReadTheDocs you linked is the old docs, we created a new one for various reasons.

https://bitburner-official.readthedocs.io/en/latest/basicgameplay/infiltration.html
There the slashing game's info is up to date
