### ISSUE TITLE
Ignore `dist` folder from git version contorl

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#129]
[Tanimodori]
Currently the `dist` folder is under git version control. The js bundle size of the project is ~17MB (`main.bundle.js`, `main.bundle.js.map`, `vendor.bundle.js`, `vendor.bundle.js.map`) and the `.git` folder is ~345MB now which is growing bigger and bigger and leads to performance drop of IDEs. Here is a list of commit numbers and `.git` folder size of popular project on github for comparisons.

| project                                            | `.git` size | #commit | size per commit |
|----------------------------------------------------|-------------|---------|-----------------|
| [`vite`](https://github.com/vitejs/vite)           | ~25MB       | ~4800   | ~5KB            |
| [`rollup`](https://github.com/rollup/rollup)       | ~24MB       | ~5000   | ~5KB            |
| [`electron`](https://github.com/electron/electron) | ~126MB      | ~26800  | ~5KB            |
| this project                                       | ~345MB      | ~7200   | ~48KB           |

This project has roughly 10x size of `.git` folder compared to other project. I see no benefits put them under git version control so I suggest removing them from git (and history maybe) before this project become unmaintainable.

**Comment by Snarling** [comment]
@Tanimodori @TheMas3212 @hydroflame 

So moving to a new repo makes it a good time to get this dealt with right from the start. I've been messing around trying to get /dist/ and /markdown/ ignored by git, but following various instructions I've found online, I'm not able to get it set up where both a) the files still exist on the branch, and b) additional changes to the files aren't tracked in git status.

Also if we did get this set up, I'm not sure exactly what building will look like since everything in the dist and markdown folders would get ignored for any commit. I'm assuming it will require a gh action set up for building game+markdown serverside, instead of building and then committing a built version? Would that even work?

Anyone have insight? I'm totally lost when it comes to most git stuff.

**Comment by TheMas3212** [comment]
from my understanding theres basicly 2 steps that need to happen
1. setup github actions to build the game and documentation and store them as build artifacts
2. rewrite git history so both folders never existed (or atleast delete them so they dont exist in the current state)

**Comment by Snarling** [comment]
So I tested with markdown, and it does not look like artifacts interact with the file system of the repo at all. The artifacts were uploaded, but they are not anywhere as files.

https://github.com/bitburner-official/bitburner-src/actions/runs/3298347442/jobs/5440343936#step:8:26

In fact I can't even figure out how to download the supposed artifacts that were uploaded. I think it would actually require making a release to attach the artifacts to. (edit: actually I think that part was just due to a syntax error I had regarding how long to keep the artifacts - but it does seem like artifacts are just for manually downloading data, not for storage in the normal file system structure)

I think artifacts might still be the correct way to do this, but the markdown may just need to be put into their own repository, e.g. bitburner-docs or something. I believe I read that there's a way to use artifacts in a workflow to commit changes to a separate repository. For now I'll restore the markdown here though.

Is there a reason the bundles can't just be removed from git here?

**Comment by Tanimodori** [comment]
> from my understanding theres basicly 2 steps that need to happen
> 1. setup github actions to build the game and documentation and store them as build artifacts
> 2. rewrite git history so both folders never existed (or atleast delete them so they dont exist in the current state)

Yes that is correct.

**Comment by Tanimodori** [comment]
Delete from history only affect `allbuild` commits and it does not matter anyway.
