### ISSUE TITLE
Ctrl+C in script editor is not Copy Selected Text

### ISSUE THREAD

**Issue by Hyratel** [bitburner-official/bitburner-src#1293]
It should be. Ctrl A/X/V all behave as expected. Ctrl C does not

I don't know what it's actually doing. 

Also, Overwrite Mode keeps kicking in and I do not want it. ESC while in Insert Mode kicks to Overwrite mode. these seem related.

**Comment by catloversg** [comment]
@Hyratel Are you talking about the vim mode (`vim script.js`)? Shorcuts like Ctrl+C/V/X/A are not supposed to work in vim. Some shorcuts (Ctrl+A/X/V) may work in some cases (in Insert mode), and it's a "convenient bug". If you use vim mode, you should not expect them to work.
I'm not sure what "Overwrite Mode" is. Vim starts in Normal mode. You can switch to Insert mode by pressing `i` or `Insert`. Pressing `ESC` to go back to Normal mode is the expected behavior.

**Comment by gmcew** [comment]
Probably worth noting the 'normal' script editor can be opened using `nano script.js`, or toggling this button in the image below. Non-vim editing mode works as you're expecting.
I'll leave this open for a bit longer in case there's extra context on the issue.

![vim toggle](https://github.com/bitburner-official/bitburner-src/assets/97335456/f6bb4670-80e4-4331-8cf1-76843577dfcf)

**Comment by Hyratel** [comment]
I was not aware that vim/nano modes were distinct. I'll have to fiddle with that; will report back

**Comment by gmcew** [comment]
I think this is resolved now so I'm closing it. If I missed something, hop over to the discord and we can re-open this
