### ISSUE TITLE
getServerNumPortsRequired always 5?

### ISSUE THREAD

**Issue by i-make-robots** [bitburner-official/bitburner-src#1359]
version 2.6.1
`ns.getServerNumPortsRequired(target);` always says 5, regardless of required ports or opened ports.
If there's a better way to determine ports needed to nuke, please let me know.

**Comment by i-make-robots** [comment]
I may have misunderstood.  pserv- reports 5 even though I have root (and don't need nuke).
I don't see an `ns.getHasRoot()` or equivalent.  
there's no way to catch a failed nuke that I can gracefully continue the script.

**Comment by d0sboots** [comment]
Personal servers, such as `home` and ones you buy, will always return 5. There's a PR sort of in limbo to change this; the problem is that there are likely other scripts relying on the current behavior. You can tell these servers because they have `ns.getServer().purchasedByPlayer === true`, among other things.

Also, you can catch a failed `nuke` with try/catch.

**Comment by i-make-robots** [comment]
Cool, thank you!  How do i tell if a server is already rooted?
What is the right way to `ns.backdoor(target)` ?
What is the right way to `ns.getServer(target).NumPortsRequired` ?

**Comment by d0sboots** [comment]
When numportsrequired <= numports...something. Or you can just try to root it and see.
