### ISSUE TITLE
Shadows of Anarchy Ares augmentation doesn't always work.

### ISSUE THREAD

**Issue by GoddessArtemis** [bitburner-official/bitburner-src#1402]
![image](https://github.com/bitburner-official/bitburner-src/assets/943237/c7a965ba-497e-4ebe-8c27-95314e4acf91)

I'm not completely sure how to reproduce it. I had trouble with this a few days ago, but it was working yesterday. Then it started again today. I'm just doing manual infiltrations, and the timer provided by the Ares augmentation is wrong.

Playing on v2.6.2dev (18ae6ce21).

**Comment by gmcew** [comment]
@catloversg I know you cleaned up some stuff in #1243 , any advice here?

**Comment by catloversg** [comment]
This problem was raised on Discord. The "cheat bar" is updated separately from the logic of the 3 phases and the main bar, so this problem is inevitable. It's fixable, but I need to refactor the logic code and the UI code of this minigame. This is really low on my priority list, so I have not done anything. I'll fix it later if nobody wants to do it.
