### ISSUE TITLE
Inconsistency in Shadows of Anarchy's price multiplier

### ISSUE THREAD

**Issue by YarikTH** [bitburner-official/bitburner-src#1406]
Version Bitburner v2.6.1 (e8a825829)

There is an inconsistency in applying price multiplier between Shadows of Anarchy and other factions.

When I buy an augmentation from the any normal faction, price multiplier of SoA stays the same. But when I do the opposite and buy an augmentation from SoA, then for some reason price multiplier for all other factions also rises. This confusion costed me few augmentations on a reset due to unexpectedly increased cost. It is not a lot, but issue is an issue.

First solution is a complete isolation. SoA augmentations affects only SoA multipliers, other factions' augmentations affects all multipliers but SoA.

Second solution is having two price multipliers for SoA. One is permanent as it is now and the second one is a common price multiplier based on number of bought augmentations that is applied for all other augmentations.

Third solution - leave it as it is. All works as intended.

**Comment by catloversg** [comment]
@d0sboots What do you think about this problem? It has been reported many times, but we have never come to a conclusion. AFAIK, the special cost of SoA augmentations is intentional (`getAugCost` in `AugmentationHelpers.ts`), but in the default branch for normal augmentations, we use `getGenericAugmentationPriceMultiplier`, and that function does not take SoA augmentations into account.
Personally, I think this is a bug. We should exclude SoA augmentations from the list when calculating the price of normal augmentations.

**Comment by d0sboots** [comment]
I think I agree, which sounds like the first option? Seems like they were meant to be special/separate.

**Comment by YarikTH** [comment]
:tada:
