### ISSUE TITLE
Inconsitent coundown on Bladeburner tasks

### ISSUE THREAD

**Issue by GoulartNogueira** [bitburner-official/bitburner-src#1479]
The (new, I guess) Bladeburner countdown is buggy.
This is specially visible when running a fast action on max Overclock.

It decreases in uneven steps:
3, 2, 1, 0
4, 1, 0
3, 1, 0
...

[Screencast from 10-07-2024 03:18:02.webm](https://github.com/bitburner-official/bitburner-src/assets/7660643/da1e5ced-4407-4284-83b1-d8c96337da71)

Expected a consistent and predictable time:
4, 3, 2, 1
3, 2, 1
3, 2, 1
...

**Comment by catloversg** [comment]
You should attach your save file.

**Comment by MaWo2** [comment]
I have observed the same in previous versions, while running operations on bonus-time with high levels of skills. The UI updated progress bar and timer every second (or tick?), but the numbers of the timer "jumped", because the tasks were performed faster.
To my understanding, bonus-time increases the speed about 5-fold. Accordingly, I got numbers like 43-38-33-...-8-3-0.
Because the last number should have been -2 (not 0), the next task even started at 41 sec.

I am now on 2.6.2 and this does not occur any longer. My time for assassination is "officially" 23 sec, but the timer goes 5-4-3-2-1-0. If I remember correctly, there was even a statement about new handling of bonus time in the changelog.
