### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (at "Documentation")

### ISSUE THREAD

**Issue by fernicar** [bitburner-official/bitburner-src#1517]
### How did this happen?
After completing the tutorial, I started to read the documentation, I noticed a typo "the Script will [weaken()] the **Script**" when it should be "the Script will [weaken()] the **server**", which make me curious to see why **Script** would have a link and I clicked it. that's it.

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Documentation
* Version: v2.6.2 (633da3830)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
* Features: lang=en-US cookiesEnabled=true doNotTrack=1 indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by d0sboots** [comment]
As near as I can tell, the string "the Script will" (with that capitalization) does not appear anywhere in our codebase. Can you copy-paste the *exact* string you encountered, or share a screenshot, or otherwise pinpoint exactly where this happened?

Aside from that, this error happens because of translation extensions. (See #527) But, we should have implemented a fix for that so that these extensions won't try to mutate the page, which is why I'm curious as to exactly what happened here.

**Comment by fernicar** [comment]
> As near as I can tell, the string "the Script will" (with that capitalization) does not appear 

Forgive me for the lack of accuracy, I should considere the screenshot from the start.
It was "our Script will...". Here is the screenshot you requested:
![image](https://github.com/user-attachments/assets/cb398f21-a106-449b-b10d-057d50cc8b17)

Here is the autosave recovery file downloaded at crash:
[RECOVERY_BITBURNER_1721879325.json.gz](https://github.com/user-attachments/files/16385307/RECOVERY_BITBURNER_1721879325.json.gz)

Thanks.

Edit: you are kind of right about translation addon. I will describe about what could have breaking the stability of the game. I'm using Edge browser to start the game, as soon as I notice a bunch of text I wonder if I could use the Read Aloud feature (Ctrl+Shift+U) and fired it several times because it didn't finish reading all the text. Maybe that remnant broke the link or something.

**Comment by d0sboots** [comment]
Thank you for the addendum. I was able to reproduce this on Edge with the following steps:

1. Enter a doc page that has a lot of text (not just the first page)
2. Start Read Aloud with Ctrl+Shift+U
3. Skip forward into the doc itself by clicking (otherwise it will spend a while reading out the overview and sidebar)
4. Click on a link to change to a new doc page (back and home won't do it)

Ultimately this seems to be the same root cause as the other bug (something is changing the dom in incompatible ways), but it isn't fixed with the `translate=no` we added because it's not related to translation. Hopefully this will be fixed when we can eventually update React.
