### ISSUE TITLE
ns.getResetInfo().lastAugReset returns incorrect value

### ISSUE THREAD

**Issue by falcazoid** [bitburner-official/bitburner-src#1533]
### Bug Description: ###

ns.getResetInfo().lastAugReset incorrectly returns absolute value instead of being direct replacement of the old deprecated function ns.getTimeSinceLastAug() as it should be (if the plan is to remove this function)

In the example script below i print the old deprecated value from ns.getTimeSinceLastAug() which returns correct value that is supposed to be the value for ns.getResetInfo().lastAugReset

### Script: ###

![image](https://github.com/user-attachments/assets/08e6ef09-1e34-4b7c-bed8-6dbea1ac87f7)

### Output: ###
![image](https://github.com/user-attachments/assets/33d685c4-5bef-4818-b800-1544e9631032)

### Time played screenshot ### 
This is only an approximate match for the script obviously as i can't really do 2 things at once - run script and do screenshot.

![image](https://github.com/user-attachments/assets/b82d0f2e-f34a-458b-9933-574e505abe36)

### Bitburner version: ### 
v2.6.2 633da3830

**Comment by catloversg** [comment]
`ns.getResetInfo().lastAugReset` is **not** the "direct replacement" of `ns.getTimeSinceLastAug()`. From NS API documentation:
- `ns.getResetInfo().lastAugReset`: Numeric timestamp (from Date.now()) of last augmentation reset
- `ns.getTimeSinceLastAug()`: Returns the amount of time in milliseconds that have passed since you last installed Augmentations.

I'll clarify this point in the deprecation warning.
