### ISSUE TITLE
Bug: Skipping Bladeburner Timer

### ISSUE THREAD

**Issue by Lower1K** [bitburner-official/bitburner-src#163]
# Skipping Bladeburner Timer
### Save File
[bitburnerSave_1666803304_BN1x3.txt (https://github.com/danielyxie/bitburner/files/9872130/bitburnerSave_1666803304_BN1x3.txt)

### Steps to reproduce
- Requires the time to complete a Contract or Operation to be 1 second, accomplished by having a high Overclock level and Bonus Time
- Start a contract (e.g. Tracking) and without canceling the contract swap to a separate action, most easily reproducible for actions under the 'General' tab. 
- If timed correctly, swapping to the action will reset its timer and allow the player to skip the time to complete. For example, can skip the one minute timer required for the 'Incite Violence' action. 
- It will then continuously take only one second to complete the action until the action is cancelled. Unsure if this works for the time on Black Ops operations.

I've noticed that what seems to be happening is that the new action that the player swaps to will inherit that previous time to complete from the previous action. It also seems to be inheriting the completion progress of the action, as in cases where the timing isn't precise, the timer for the new action will still end up with partial progress.

### Version of the game
Bitburner v2.1.0 (8f4636cb)

**Comment by Snarling** [comment]
The fact that you state "Requires the time to complete a Contract or Operation to be 1 second, accomplished by having a high Overclock level and Bonus Time" makes me think you may just be describing the normal operation of bonus time overflow.

Every 1 second while you have bonus time available, bladeburner will process 1s of actions normally, and will also consume 4s of your bonus time and add that to whatever active timer you are working on.

When the player is performing a task that takes less than 5s, this would normally result in wasted bonus time. Instead, the game places this overflow of time into a separate buffer - and then if the player switches to a task that takes longer than 5s, the extra time in this buffer will be instantly used towards that other task.

example: Player has 4 hour of bonus time. For 1 hour, the player does tasks that take an average of 2s per action. 1 hr of bonus time would be consumed during this hour, and 3 hours of bonus time would end up in this extra overflow buffer, and the player would be out of bonus time.

Player then switches to a task that takes 1 minute to perform. This task will only take 1s to complete (but will still show 60 seconds as the time required) for just over 180 completions, as performing the task consumes time from the buffer at a rate of 59s per 1s in order to apply 60 seconds of progress per 1 second. After there is no more time left in the buffer, action completion will proceed at a normal rate.

Can you confirm if this is what you're talking about?

**Comment by Lower1K** [comment]
Yes, this is what I was talking about. I was unaware of the overflow buffer being a mechanic in the game and is why I misclassified this as a bug. I appreciate the clarification and I'll be closing the issue.
