### ISSUE TITLE
Error using `ns.exec()` 'args' is not an array of script args

### ISSUE THREAD

**Issue by Sebbito** [bitburner-official/bitburner-src#1669]
# Writeup

Basically my issue is using the `args`  field of the `ns.exec()` function.
I currently use an abstraction that looks like the script below.

I get the error: `exec: 'args' is not an array of script args`

I've looked at the checks that are used to determine if `args` truly isn't
an array of `ScriptArg` but all my checks pass in accordance to the checks
that are performed in the source:
https://github.com/bitburner-official/bitburner-src/blob/dev/src/Netscript/NetscriptHelpers.tsx#L426

Maybe I don't understand something about JS or the function but for now it
seems like there is a bug :shrug: 

# Info

Version: Bitburner v2.6.2 (633da3830)

Save: [bitburnerSave_1727559047_BN1x1.json.gz](https://github.com/user-attachments/files/17176653/bitburnerSave_1727559047_BN1x1.json.gz)

Steps to reproduce:
- open game with save file and run `run test.js`

Minimal scripts to reproduce the issue:
```js
/** @param {NS} ns */
export async function main(ns) {
  // assumes you have  a script named `hack.js`. Contents don't matter
  let server = ns.getServer('n00dles');
  run_script(ns, server, "hack.js", 1, server.hostname);
}

function run_script(ns, server, script_name, amount, ...args) {
  if (amount > 0) {
    // checks also performed in source
    ns.tprint(Array.isArray(args));
    args.every((arg) => ns.tprint(typeof (arg)));
    // here the error occurs
    ns.exec(script_name, server.hostname, amount, args);
  }
}
```

**Comment by d0sboots** [comment]
There's several confusing things going on here. I blame most of this on a subtlety of TS, and as a result, the documentation. If you see the docs for exec (https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.exec.md), it lists the signature as:
```js
exec(script: string, hostname: string, threadOrOptions?: number | RunOptions, ...args: ScriptArg[]): number;
```
The `...args` means that the remainder of the arguments are gathered into an array named "args", which will be of type `ScriptArg[]`, i.e. the remaining arguments should each be of type `ScriptArg`. If you only look at the parameters block below, it is easy to overlook this.

The fix is simple, call exec like this: `ns.exec(script_name, server.hostname, amount, ...args);`

**Comment by Sebbito** [comment]
Damn i was a 100% certain that i checked that possibility. My bad for overlooking this and thanks a lot!

**Comment by MakkuSaiko** [comment]
Thank you so much. Im still new to JS and TS so I was racking my head trying to figure out why I can't pass my array despite it seeming like the method accepts an array. Anyone still confused syntax for array is func(...args) vs for single/comma seperated: func(arg)/func(arg1, arg2). The 3 dots must be used when passing an array to indicate array

**Comment by d0sboots** [comment]
What's actually going on is that the 3 dots must be used to spread the array out into individual args (it is known as "spread syntax"), and then they are re-gathered into an array due to the 3 dots on the function prototype side. (Reuse of the same syntax is slightly confusing, but it's not ambiguous and lots of languages do it that way. )
