### ISSUE TITLE
Save Load is Fucked

### ISSUE THREAD

**Issue by dopefish2112** [bitburner-official/bitburner-src#1675]
# DELETE THIS AFTER READING

# include (where relevant)

V 2.6.2 playing on steam

Steps to recreate 

Save your game

Load last save

That's it. Lost all progress. Searched all local save locations and found none.

**Comment by d0sboots** [comment]
Do you remember if there was any pop-up? This sounds like the save failed. 

If you want to be extra certain, you can export your game. The game gently encourages you to do this every day (via a small bonus) so that you'll have backups.

**Comment by catloversg** [comment]
@d0sboots This issue was also reported on Discord by the same player. It seems that the save data was overwritten by an earlier save. There is no other useful information. I suspect that there is a hiccup with Steam Cloud sync, but I'm not sure if it's a problem in our code. I don't think we can do anything here.
