### ISSUE TITLE
Implement more sh syntaxes

### ISSUE THREAD

**Issue by farooqkz** [bitburner-official/bitburner-src#1731]
Hello there! I made a post on Mastodon about addictive FOSS games and someone suggested BitBurner. Great work folks!

It could be fun to implement some other sh(and NOT bash!) syntaces. like usage of `&&` and `||` and maybe some `for` loop. Then we could do `hack && hack && hack` to do the hack 3 times!

**Comment by d0sboots** [comment]
Yes, the shell is (somewhat intentionally) very rudimentary. The idea is to encourage the user to write .js scripts to do things, rather than having such a full-featured shell that people would be tempted to write .sh scripts. In addition, the actions you can do manually are actually different from what you can do via the APIs, until you unlock some stuff later on. So if you could make for loops and whatnot in the shell, that would cut against the current progression model a bit.

**Comment by farooqkz** [comment]
Alright. Closing this as invalid.
