### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by LJNeon** [bitburner-official/bitburner-src#185]
- [x] `html-webpack-plugin`: 3.x is no longer supported
  - [ ] `asar`: Please use @electron/asar moving forward.  There is no API change, just a package name change
  - [ ] `electron-notarize`: Please use @electron/notarize moving forward.  There is no API change, just a package name change
  - [ ] `electron-osx-sign`: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
  - [ ] `w3c-hr-time`: Use your platform's native performance.now() and performance.timeOrigin.
  - [ ] `chokidar`: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
  - [ ] `querystring`: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
  - [ ] `fsevents`: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
  - [ ] `uuid`: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  - [ ] `source-map-resolve`: See https://github.com/lydell/source-map-resolve#deprecated
  - [ ] `resolve-url`: https://github.com/lydell/resolve-url#deprecated
  - [ ] `urix`: Please see https://github.com/lydell/urix#deprecated
  - [ ] `source-map-url`: See https://github.com/lydell/source-map-url#deprecated

**Comment by Snarling** [comment]
For some of these, I think we will need to upgrade to webpack5 (which we should do at some point anyway) for us to update all of the dependencies. I've tried before but I was not able to get everything working on webpack5 at the time.

Here's one example where updating webpack is probably the only way to update dependencies: https://github.com/webpack/watchpack/issues/199

So rather than individually attempting to address each of these deprecated dependencies, I think the correct move is to first update to webpack5 and get everything working in that environment, and then it should be much simpler to update any remaining dependencies from there.
