### ISSUE TITLE
Wrong script ram usage calculation with library exported classes

### ISSUE THREAD

**Issue by AtomikPunk** [bitburner-official/bitburner-src#1886]
Hi there!

First of all, thanks for this awesome game!

I encountered what seems to be a bug in the ram usage calculation when using exported classes from a library. It appears as if the calculation of a script always include all classes from a library even if I only import one specific class from it.

At first I thought it was the naming of the method that caused problem but as you can see below, I renamed the method to a different name with no better result.

Is this a bug? I really prefer object-oriented programming and would love to play BitBurner this way if possible.

Many thanks!

# Relevant information
- [ ] Save file
_Irrelevant_

- [x] Minimal scripts to reproduce the issue
## bug_lib.js
```js
export class SomeClass {
    Run(ns) {
        ns.print(ns.getPlayer().money);
    }
}
export class TotallyUnrelatedClass {
    Run2(ns) {
        ns.print('hello');
    }
}
```
## bug_script.js
```js
import { TotallyUnrelatedClass } from "bug_lib";
export async function main(ns) {
    let c = new TotallyUnrelatedClass();
    c.Run2(ns);
}
```
## Result
```
[home /]> mem bug_script.js
This script requires 2.10GB of RAM to run for 1 thread(s)
  1.60GB | baseCost (misc)
  0.50GB | getPlayer (fn)
```

- [ ] Steps to reproduce
_Irrelevant_

- [x] Version of the game
BitBurner (Steam) v2.7.0 (fbe1546fd)

**Comment by d0sboots** [comment]
This is halfway between a bug and an unfortunate feature. Classes have static initializers that run when they are evaluated (as opposed to when they are instantiated), and the static RAM check is conservative, so unlike with free functions, all RAM use within a class will be pulled in.

There are several ways of working around this; the simplest one is to split up your classes so they are one per file (which is generally good practice, anyway). For dealing with differences caused by different sets of methods called, you typically have to either use free functions or RAM overrides.

**Comment by AtomikPunk** [comment]
Thanks for the explanation, makes sense!
