### ISSUE TITLE
Basic documentation not maintained well

### ISSUE THREAD

**Issue by kingrodriguez** [bitburner-official/bitburner-src#275]
Bitburner v2.2.0 (680027cd)

the following documented functions can nowhere be found. which is in issue in the second case because of the jobs and tor purchased.

https://bitburner-beta.readthedocs.io/en/latest/netscript/singularityfunctions/getStats.html
https://bitburner-beta.readthedocs.io/en/latest/netscript/singularityfunctions/getCharacterInformation.html

also the `upgradeHomeCores()` method is implemented, but not documented in the docs.

**Comment by Snarling** [comment]
Yeah those "basic" docs aren't updated as well as they should be. The actual, full ns documentation is at https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.md

Leaving this issue open, the basic docs do still need to be updated.

**Comment by Snarling** [comment]
The "basic" documentation lives at https://github.com/bitburner-official/bitburner-src/tree/dev/doc/source for anyone looking to improve that documentation.

**Comment by kingrodriguez** [comment]
the question is: proceed with two/three (if you include the beta docs) docs or keep one and remove the others?
i suggest rtd only for easy version changing including beta branches for test best result.
but the markdown version is faster and easier to maintain - versionchange via tags / branches.
any preferences?

**Comment by Snarling** [comment]
Yeah the markdown version is already autogenerated from NetscriptDefinition.d.ts, which must match the actual API or else typescript will fail to build the game. So to some extent it is automatically maintained.

The autogenerated nature of it does make it difficult to have anything other than the actual raw documentation on ns functions/interfaces/etc., things like "beginner's guide" or "recommended bitnode order" or "corporation guide".

But right now the "basic documentation" includes both these custom-written guide type things, and also documentation for functions. So we can remove the function documentation from there at least because the function docs are in the autogenerated md files.

**Comment by Mughur** [comment]
I'm working on renewing the docs.
Also as in the original post you linked two functions from the *beta* version's read the docs, which is multiple *years* old.
The information you get from both of those linked functions are in the current `getPlayer()` function.

`singularity.upgradeHomeCores()` is a singularity function, none of them are documented in the basic docs
