### ISSUE TITLE
Coding contract window lost due to singularity function

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#28]
[macdjord]
I had a coding contract window open when a script I had running in the background called the exercise-at-gym singularity function. This caused the game to switch to the gym training screen and the contract window to vanish. When I went back to the terminal and tried to reopen the contract by running it again, I got an error message saying "There's already a Coding Contract in Progress". I had to reload the game to get the contract open again.

Version: Bitburner v1.3.0 (9fdc3ac5)

**Comments From Original Issue**

[SagePtr]
> Also contract window disappears when you return your focus to faction job (hacking contracts for instance) when coding contract window is opened. You cannot programmatically solve contracts after this (the game thinks contract is running) until you reload the game.

[nulflux]
> This also happens when triggering a DOM click() on a menu option like City as the contract window is open. The coding contract is forever in progress and there is no way to return to it. There are two potential solutions for this: 1) instead of an error the run command could default to cancel and re-open the contract or 2) make available a command to cancel the current contract. Solution 1 solves the problem universally; solution 2 allows the users to solve the problem themselves. Since there is no special mechanic preventing players pre-singularity from running a coding contract programmatically I don't believe it should be a singularity function but rather a function available by default.

[phyzical]
> idk if this should be fixed, by changing focus is it not expected to close windows?
> 
> or is it more of a the window should be there when you go back to the terminal?

[macdjord]
> @phyzical The problem isn't that the window closes. The problem is you can't reopen it because the game thinks its still open.

[BrianLDev]
> This bug happened to me today too in the way @SagePtr described.
> 
> If you have a contract open and change focus to Faction work, the coding contract UI disappears but the game incorrectly thinks that it's still open.  Doesn't look like there's a way to get the UI to pop back up again, and trying to run the contract again gives an error message. `There's already a Coding Contract in Progress`.  The only way to fix it is to close and reopen the game.
> 
> <img width="443" alt="image" src="https://user-images.githubusercontent.com/16980550/154361545-78437e85-7198-4358-9863-6d588d21583e.png">

[BrianLDev]
> So I'm guessing the fix would be in the code that handles focus.  It should check for any open coding contracts and simply close them before changing focus.

[macdjord]
> @BrianLDev That seems like treating the symptom rather than the problem to me. A better solution would be to change the 'is a coding contract in progress' check so it actually checks whether there is a contract window open - as in, examine the DOM - rather than depend on finding every possible way that the contract window could get closed and ensuring each one marks the window as closed first.

[holgero]
> Why is there a guard against opening the contract again, anyway? Perhaps just delete that?

[rayanth]
> @holgero it was likely intended in order to prevent two _different_ coding contracts from being opened at the same time. I agree with @macdjord that the better fix would be in the check for a coding contract in progress, but rather than simply check if a window is open, check if a _different_ contract's window is open. If the same coding contract's window is thought to be open, just display it again.

[YoshiRulz]
> Just hit this on 2.0.2 via Steam.

**Comment by Snarling** [comment]
Probably an issue in the component that handles displaying the contract, not cleaning up properly when forcibly closed (cleanup can be done via a useEffect return)

**Comment by myCatsName** [comment]
> Probably an issue in the component that handles displaying the contract, not cleaning up properly when forcibly closed (cleanup can be done via a useEffect return)

The location I'm looking at is https://github.com/bitburner-official/bitburner-src/blob/dev/src/ui/React/CodingContractModal.tsx#24

`interface CodingContractProps {
  c: CodingContract;
  onClose: () => void;
  onAttempt: (answer: string) => void;
}
`

and the promises referenced here https://github.com/bitburner-official/bitburner-src/blob/2c0f7f1eda8e0519e89f342a860830182892a83c/src/CodingContracts.ts#L156C10-L156C10

` async prompt(): Promise<CodingContractResult> {
    return new Promise<CodingContractResult>((resolve) => {
      CodingContractEvent.emit({
        c: this,
        onClose: () => {
          resolve(CodingContractResult.Cancelled);
        },
`

I have tried adding cleanup return to the modal component's existing useEffect, but can't get the right behavior at all. I think cleanup needs to resolve the contract as cancelled, maybe . Lack of React (and general code) experience and I might be missing other ideas. Examples I've tried (close() is a function within the CCT modal component)

`  useEffect(() => {
    CodingContractEvent.subscribe((props) => setContract(props));
    return ()=>{close}
  },[]);` 

And other ways avoiding the close fx, for example

` useEffect(() => {
    CodingContractEvent.subscribe((props) => setContract(props));
return ()=> {console.log('CCT modal unmount') ;setContract(null); contract?.onClose;}
  },[]);`

PS, I will attach gotogym.txt, a js script I used to replicate the bug. run gotogym.js, leave the tail open; open a CCT; run gotogym.js using the tail; the CCT was forced shut and gotogym has moved focus back to terminal; Now, attempting to run a CCT will produce "there's already a contract in progress" bug.
[gotogym.txt](https://github.com/bitburner-official/bitburner-src/files/12264623/gotogym.txt)

**Comment by myCatsName** [comment]
I think this is relevant console error for this bug: `React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function`

![image](https://github.com/bitburner-official/bitburner-src/assets/141260118/06dd93bc-3583-4e25-8f84-f5414037c944)

It seems specifically to appear the "next" time the CCT modal is opened (if possible) after a "focus interrupting" process was used, like my gotoGym script. In other words, `run contract-756974.cct` alone produces no error, `run gotoGym.js` no error. But if CCT is run and closed, _then_ gotoGym is run (and finished), now re-opening CCT modal should show this error. No error if instead a "non-interrupting" script is run instead of gotoGym.

**Comment by myCatsName** [comment]
I have a partial fix to the first part of this problem, and continuing work...

this is enough to cancel the contract when interrupted, eliminating the need to "refresh" BB to open a CCT modal. ATM the above console React error message is still thrown, so I am investigating. But happy to finally make a step in the right direction. I am also seeing discussion about the error message possibly being a React thing. IF the functional bugs are fixed, the error is in console only and may not affect the player. But currently this code causes other problems. I'm struggling to master useEffects lol

`  useEffect(() => {`
`    CodingContractEvent.subscribe((props) => setContract(props));`
`    return () => {contract?.onClose()};`
 ` },);`

I'm thinking there need to be 2 useEffect functions, because the return function should do onClose and unsubscribe from the event props (possible fix for the React console error?) only on unmount and needs `[]` dependency; but the event subscriptions need to constantly render with no dependency array, or the input field is unusable and defaults back to terminal.

**Comment by myCatsName** [comment]
OK I think I might have it here, with 2 useEffects I seem to have a fix. 

`  useEffect(() => {`
`    CodingContractEvent.subscribe((props) => setContract(props));`
`  },);`
`  useEffect(() => {`
`    return () =>{contract?.onClose()};`
`  },[contract]);`

- Input field works, submission pass fail works, copypaste works.
- When the CCT modal is closed by interruption, terminal prints the contract was cancelled and can be re-opened as normal.
- Tested with gotogym, .click(), and using the overview "focus" method, or alt+E to editor, all the situations described in the issue here.
- Really should be tested by others, because I have had a variety of behaviors during the time I worked this out, some of which would be very undesired. I will post a PR soon after a bit of clean up

**Comment by Snarling** [comment]
Fixed by #716
