### ISSUE TITLE
Game stopped working after update

### ISSUE THREAD

**Issue by gzarpapis** [bitburner-official/bitburner-src#282]
- [ X ] Save file:  https://we.tl/t-t2tMDjlcLF
- [ v2.2.0 ] Version of the game

**Comment by Mughur** [comment]
hot fix now live, try again

**Comment by gzarpapis** [comment]
Same problem unfortunately, can't get past recovery mode. Re-installing didn't work either.

**Comment by Snarling** [comment]
Taking a look now

**Comment by Snarling** [comment]
Can you upload your save to a site that doesn't look illegitimate

**Comment by Snarling** [comment]
You can also just upload it here by dragging the file into a comment.

**Comment by gzarpapis** [comment]
Is this uploaded?

**Comment by gzarpapis** [comment]
Im having trouble attaching the json save file, if wetransfer is not acceptable where should I upload it?

**Comment by Snarling** [comment]
It's all good I went ahead and downloaded it, I just had to do some searching to make sure it's a legit site lol

There's a build that fixes your load issue up at https://bitburner-official.github.io/bitburner-src/ now

Steam should also be updated, you may need to close and relaunch steam to get it to recognize there's an update.

Also note you'll end up with an error in one of your scripts due to the API change where ns.corporation.getCorporation().divisions is now just the names of the divisions, not their info. You'll need to also use ns.corporation.getDivision for that
