### ISSUE TITLE
All employees stopped working in latest update and revenue = 0 for corporation

### ISSUE THREAD

**Issue by casperes1996** [bitburner-official/bitburner-src#286]
I've attached a save game from the latest update in which the bug is happening, as well as the latest backup I had from before the update where employees worked.

It seems that the change to the way employees work has completely halted my corporation. None of them work, their morale and happiness is at 0, my business is generating 0 revenue now, down from about 10b/s
s and all of this happened immediately upon entering the game after everything was running smoothly last night. I have immediately quit out after quickly trying to fix it by unassigning workers and re-assigning them (no effect). I was using Smart supply chains and in some sectors Market TA. - There is supplies to make new products with but no products are being produced. 
While I used automatic employee management, the removal of individual employees also feels like a downgrade, but that's besides the point. 

As it stands right now, the entire corporation mechanic seems non-functional; At least for a corporation that was started before the update

PS. I've changed the extension of the save games to txt to allow GitHub uploading. LatestBB2 is the most recent, post-update version
[latestBB2.txt](https://github.com/bitburner-official/bitburner-src/files/10335905/latestBB2.txt)
[LatestBB.txt](https://github.com/bitburner-official/bitburner-src/files/10335906/LatestBB.txt)

**Comment by Snarling** [comment]
> None of them work, their morale and happiness is at 0, my business is generating 0 revenue now, down from about 10b/s

You now have to actually buy Coffee and Parties, you can't just ignore those mechanics. Here is your corporation after fixing just your software industry, by purchasing the AutoPartyManager research and purchasing coffee a few times:

![image](https://user-images.githubusercontent.com/84951833/210396822-a3f94533-8d25-41b0-a0af-4a3ddd3dde0f.png)

For the divisions that can't afford autopartymanager but they have decayed to 0 happiness/morale, throwing a party for 18,000,000 per employee in each office is enough to go all the way from 0 to 100 on those stats in one go. It does get a bit ridiculous when you have to manually do this for so many offices, so it's recommended that before you expand a corp too broadly, you get access to the Office API so you can automate this (or you just get the AutoPartyManager and AutoBrew upgrades before expanding to a new industry).

But yeah you can't just ignore the employees anymore, it's an intentional change.


You should automatically have access to the Office API because you're in BN3, but for some reason that's not working correctly. I'll look into that and try to get a fix out.

The stats are also not supposed to decay all the way to 0 - I had added a minimum value of 5 but for some reason it is not working correctly. Will try to get a fix for this out as well.

**Comment by Snarling** [comment]
Alright I have a fix for the minimum employee stats that will be uploaded shortly. Here is what loading your latestBB2.txt save looks like with this fix in, before doing any kind of party/coffee management (still very profitable even though employees are at 10 happiness/morale). You will still want do something to manage their stats though.

![image](https://user-images.githubusercontent.com/84951833/210403144-e2ea3bd4-6dba-4c22-a694-af5c83a2e73a.png)

**Comment by Snarling** [comment]
The new build up at https://bitburner-official.github.io/bitburner-src/ has the fix for minimum decay stats now.

Fix is also up on steam now.

For the Office API thing I mentioned above, future runs of BN3 will grant you the APIs for free, but since you already had a corporation when you loaded the new version, it doesn't apply this time around. You do have plenty of corp money to purchase the APIs though.

**Comment by casperes1996** [comment]
I see. Thanks for looking into it and informing me of the intentional and unintentional parts of this change. I read through the changelog for the update and this change was not very well described. I would consider this a bug report on informing the player base of such a big change.

Thanks again.
