### ISSUE TITLE
Player is charged ram cost for using variable/property/function names of ns functions

### ISSUE THREAD

**Issue by RiversJohn** [bitburner-official/bitburner-src#298]
Bitburner 2.2.1 : c46cedd5

Below test script will result in an additional 150mb RAM cost for the script due to line 25 call to readback.weaken
Being a C# programmer not a JS guy i can't offer too much insight as to what's going on but i'd imagine this is due
to dynamic typing and inability to type resolve calls so the mem function simply looks for .weaken maybe?

```
/** @param {NS} ns */
export const weakenSecBoost = 0.05;
export const growSecCost = 0.004;
export const hackSecCost = 0.002;
export const globalPort = 1;

export async function main(ns) {
    var globals =
    {
            "weaken": weakenSecBoost,
            "grow": growSecCost,
            "hack": hackSecCost
    };

    var globalsJSON = JSON.stringify(globals);

    var globalsPort = ns.getPortHandle(globalPort);

    await globalsPort.write(globalsJSON);

    var readback;

    readback = JSON.parse(await globalsPort.read());

    ns.tprint(readback.weaken);
}

```

**Comment by Snarling** [comment]
Any ns function names are essentially reserved keywords if you don't want to pay their ram cost. For the time being there's no way around this, and would require a significant ramcost system rework to make it so it does not work like this.

As a workaround you can write that as readback["weaken"] to avoid the ramcost.

**Comment by Snarling** [comment]
This was partially fixed by the addition of the [ramOverride](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.runoptions.ramoverride.md) property on [runOptions](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.runoptions.md), which can take the place of the threads argument for [ns.run](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.run.md), [ns.exec](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.exec.md), etc

This is the extent to which this is really able to be addressed, so I am closing the issue. Sorry this is not a more complete fix, but there are limitations we have to work within.
