### ISSUE TITLE
kill(...) in game documentation is confusing, as there are 2 versions.

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#356]
In the script editor the tooltip for ns.kill( only mentions a script number argument.  That made me think it was local only.  But I've found a file with _1 in the name that seems odd.  I wonder if the old file wasn't overwritten like it should have been?  Or...?

https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.kill.md - is what I saw in the script editor.
https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.kill_1.md - is what I'd expected to see instead.

Maybe this is an attempt to get rid of an optional parameter by writing two?  Or work around some other oddity?

I can figure things out for my needs, but wanted to mention it in case it should be improved somehow.  I don't see a lot of duplicated method names with different argument counts in the public API.

**Comment by OneOfMany07** [comment]
Random other thought...it's frustrating I must specify all arguments in the kill(...) call for remote hosts.  On the command line I can kill processes by matching the script name alone.  Through code it seems I must kill everything or know exactly what I ran.

I'm sure I can write a solution, and maybe that's the goal with the limitation (to prod people to code a bit more)...

**Comment by Mughur** [comment]
The first one is `kill(PID)`
The second one is `kill(scriptName, serverName, args)`
They are both completely valid. Always have been, always will be.

> Random other thought...it's frustrating I must specify all arguments in the kill(...) call for remote hosts. On the command line I can kill processes by matching the script name alone. Through code it seems I must kill everything or know exactly what I ran.

If you kill a process through the command line you need to know the scripts arguments. The kill command/function needs to know which exact script you want to kill, either by giving it the script's PID or giving the script's identifying information (i.e. name, server, arguments if any).

There are generally 2 ways of getting the PID of some script:
-the return value of `exec`/`run`
-`ps(server)`, which can also be used to get the script's name and arguments.

I'm not totally sure why that has two pages and other similar cases only have one

**Comment by OneOfMany07** [comment]
Sorry I was mixing up how tail helps us out.  Letting you skip arguments if you specify a unique running script name.

It'd be nice to unify the kill options.  Meaning allow anything remotely that works locally, including a remote valid PID number as the kill target.  I'd assume most implementations would be created that way.  Take however you kill things locally, wrap it and pass it what it needs for the remote version.

I wonder if this separation happened to avoid an optional argument or two?  I've already run into a situation where I wanted to leave out a middle optional entry...since we can't specify what an argument is for, like with assignment (blah='value' or I failed back when I attempted it). 

So I'd revise my opinions to include...
- Would be nice to allow all the same kill inputs to work local and remotely (allow PID based remote killing).  No idea if this is on purpose for game balance, or ...?
- Having 2 help pages means if you need the 2nd page you're out of luck...or I didn't see how to read the second page.  Nor did I even know that was possible (that the game had any overloaded API calls).  That'd be another motivation to merge the two into a single API.

But I get it this might be lower priority.  Thanks for sharing your thoughts @Mughur !

**Comment by Mughur** [comment]
>  Would be nice to allow all the same kill inputs to work local and remotely (allow PID based remote killing). No idea if this is on purpose for game balance, or ...?

that's exactly what the `kill(PID)` is. `PID` is global, not local. If you use `ns.kill(PID)` on any server it'll kill the script that has the given `PID`. If you use `kill PID` in terminal it'll kill the scrip that has the given PID. Neither of these cases care which server the script is running on or on which server you run the command / use the function.

> Having 2 help pages means if you need the 2nd page you're out of luck...or I didn't see how to read the second page. Nor did I even know that was possible (that the game had any overloaded API calls). That'd be another motivation to merge the two into a single API.

In the API they are the same, again, I don't know why kill has two pages when no other function does (even those with similar/same options only have one page)

**Comment by Snarling** [comment]
Overloading does not actually exist in js in that under the hood there is always only one actual function. Instead, multiple documentation entries can be used for the same function in order to show the different ways of using a function.

This isn't specific to Bitburner. Many builtin js functions also have multiple documentation entries to show the different ways they can be called.

You can cycle between the versions using an up/down button. Here's what the ns.kill second entry looks like in the ingame editor:
![image](https://user-images.githubusercontent.com/84951833/218613691-8c98f7d5-e6df-4ccf-898d-326e71991140.png)

That documentation is sort of broken, so that does actually need to be fixed. The first ingame doc is similarly lacking information that it should have: 
![image](https://user-images.githubusercontent.com/84951833/218617183-265d0fb9-03ee-4c28-a807-e912decd6ee7.png)

>I wonder if this separation happened to avoid an optional argument or two?

With just optional arguments, it's not clear that when you provide a pid, you don't need to/shouldn't provide any other arguments. With two separate function signatures, it's clear that if you're using a pid, that's all you need to provide, but if you're providing a scriptName, then you also need to specify a server and specific script args to identify the specific script. In this cases, because it's basically two entirely different ways to use the function, it needs to be documented as two different functions.

Reopening because I'll be submitting a PR to improve these docs. It's not an issue that there are two entries, but it is an issue that they don't provide the info they should.
