### ISSUE TITLE
Using translation extensions causes React errors

### ISSUE THREAD

**Issue by CherrySaito** [bitburner-official/bitburner-src#358]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Terminal
* Version: v2.2.1 (238a4357)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
* Features: lang=ja cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by TheMas3212** [comment]
Were you doing any sort of DOM manipulation when this happened?

**Comment by Snarling** [comment]
It's because you're using google translate or some other translation extension. That doesn't play well with React and causes issues like this.

Basically your translation extension is modifying the DOM structure (moves translated text into a new element) and React is no longer able to perform its own DOM manipulation on that text node because it can't locate it anymore.

For now the only workaround is just not using translation extensions. Sorry for the inconvenience.

**Comment by Snarling** [comment]
See #527 which has some additional info in the comments. Closing this one and keeping 527 open to track the issue.
