### ISSUE TITLE
Enabled Market-TA II and sell price stays $0.000 (and amounts)

### ISSUE THREAD

**Issue by OneOfMany07** [bitburner-official/bitburner-src#377]
Have a corporation with a Software unit.  Have 3 products that aren't great, and I'm a bit early on still so the value of my products are low.  Apparently my Market TA II price is lower than the Market TA I price (on at least one product).  Earlier I was selling at MP.  With Market TA I was fine.  Didn't help much, but oh well.

Next turned on Market TA II and all prices (the yellow ones for last used) all became 0 and aren't changing.  I see corporation cycles happening at the top, but no products appear (so not building without selling).  And the revenue value hasn't changed much...it's not 0 either.  Though I never see products being made and sold down below, like I usually do briefly.

Maybe this is just the value shown is 0 instead of the real value?

**Comment by Mughur** [comment]
Sounds like you aren't producing the products. make sure you are buying enough materials (if you have Smart Supply on this happens automatically) and that you have enough space for the production to take place. Also in order to TA1/2 work you have to set sell amount and price (the price will be overwritten, but you can't set the amount without setting the price) before turning on TA1/2

**Comment by OneOfMany07** [comment]
Doh, that was it.  Only was 0 in the default Sector 12 location.  I'd forgotten to manually enable Smart Supply on that initial spot.

I am still confused why it showed a price without that feature on, and switched to 0 when on...  But it's getting narrower and narrower if it is an actual issue.
