### ISSUE TITLE
Race condition in `compile`

### ISSUE THREAD

**Issue by d0sboots** [bitburner-official/bitburner-src#444]
The following script demonstrates the issue. Running it produces the following:
>RUNTIME ERROR
> import_test_generated2.js@home (PID - 35)
> 
> Failed to fetch dynamically imported module: blob:http://localhost:8888/757b1b83-6450-44fb-bcf6-8770dd28964a
stack:
> TypeError: Failed to fetch dynamically imported module: blob:http://localhost:8888/757b1b83-6450-44fb-bcf6-8770dd28964a

```js
/** @param {NS} ns */
function createScript(num, ns) {
  ns.write(
    `import_test_generated${num}.js`,
    (num == 2 ? 'import "import_test_generated1.js";\n\n' : '') +
    `
/** @param {NS} ns */
export function main(ns) {}
    `.trim(),
    "w"
  );
}

/** @param {NS} ns */
export async function main(ns) {
  createScript(1, ns);
  createScript(2, ns);
  ns.run("import_test_generated2.js", 1, 1);
  const promise = Promise.resolve().then(() => {
    ns.run("import_test_generated1.js");
    ns.run("import_test_generated2.js");
  });
  ns.run("import_test_generated2.js", 1, 2);
  await promise;
}
```

The problem is a race condition in `compile` (in NetscriptJSEvaluator.js). I think that whole function needs a rework, I don't see a way it can be patched and still have high certainty that it won't have other race conditions.

**Comment by Snarling** [comment]
Good catch. I thought that function was bulletproof. Even with that code clearly hitting a race condition, it was difficult for me to see how it might be occurring.

As far as the rewrite, going back to a discord topic a rewrite here also allows us to solve one of two major inconsistencies with the expected behavior of js:

1. Import loops don't work (e.g. A imports B imports C imports A) in cases where they should.
2. Files do not maintain the same module when they are imported by different scripts.

Unfortunately as you mentioned on discord we can probably only solve one of these inconsistencies. Personally I think we should solve number 2 and just create a better error message for number 1 (the current error is just a stack size limit error I think). What are your thoughts?

**Comment by d0sboots** [comment]
2 is difficult, especially if you want to do it across servers, but I think I have a design worked out.

At this point, I think 1 is downright impossible, or very close to it, because of how Blobs are immutable. I think the right answer there is detecting the loops (instead of overflowing the stack) and better error messaging, including pointing towards use of `import.meta.url` with dynamic `import()` for cases where a circular import can't be avoided.

I expect to work on this soon, once I figure out testing for NS2 (or give up again)
