### ISSUE TITLE
Growing an empty server (server with 0 money) still problematic

### ISSUE THREAD

**Issue by rlpowell** [bitburner-official/bitburner-src#451]
Bitburner v2.2.2, steam version.

I noticed this issue because my script errored out on the following line:

		var grow_goal = (ns.getServerMaxMoney(target_name) / ns.getServerMoneyAvailable(target_name));

Which, OK, fine, but then I was trying to figure out *how* to set a growth goal, when growAnalyze is expressed only in terms of a *multiple* on the current amount of money, which was 0.

Here's what happened when I tried to do it manually:

```
[neo-net ~/]> analyze
Analyzing system...
[||||||||||||||||||||||||||||||||||||||||||||||||||]
neo-net: 
Organization name: Neo Nightclub Network
Root Access: YES
Can run scripts on this host: YES
RAM: 32.00GB
Backdoor: NO
Required hacking skill for hack() and backdoor: 50
Server security level: 8.000
Chance to hack: 84.68%
Time to hack: 18.337 seconds
Total money available on server: $0.000
Required number of open ports for NUKE: 1
SSH port: Open
FTP port: Closed
SMTP port: Closed
HTTP port: Closed
SQL port: Closed
[neo-net ~/]> grow
[||||||||||||||||||||||||||||||||||||||||||||||||||]
Available money on 'neo-net' grown by ∞%. Gained 10.500 hacking exp.
Security increased on 'neo-net' from 8.000 to 8.100
[neo-net ~/]> analyze 
Analyzing system...
[||||||||||||||||||||||||||||||||||||||||||||||||||]
neo-net: 
Organization name: Neo Nightclub Network
Root Access: YES
Can run scripts on this host: YES
RAM: 32.00GB
Backdoor: NO
Required hacking skill for hack() and backdoor: 50
Server security level: 8.100
Chance to hack: 84.59%
Time to hack: 18.490 seconds
Total money available on server: $25.552
Required number of open ports for NUKE: 1
SSH port: Open
FTP port: Closed
SMTP port: Closed
HTTP port: Closed
SQL port: Closed
[neo-net ~/]> 
```

This seems to have been fixed with https://github.com/danielyxie/bitburner/issues/2635 and various issues that that points to, but here we are, not sure what's up.

**Comment by rlpowell** [comment]
After that:

```
[neo-net ~/]> hack
[||||||||||||||||||||||||||||||||||||||||||||||||||]
Hack successful on 'neo-net'! Gained $0.000 and 10.500 hacking exp
Security increased on 'neo-net' from 8.002 to 8.004
```

Which is not great, because it does in fact have $25.552 according to analyze.

```
[neo-net ~/]> analyze 
Analyzing system...
[||||||||||||||||||||||||||||||||||||||||||||||||||]
neo-net: 
Organization name: Neo Nightclub Network
Root Access: YES
Can run scripts on this host: YES
RAM: 32.00GB
Backdoor: YES
Required hacking skill for hack() and backdoor: 50
Server security level: 8.002
Chance to hack: 84.68%
Time to hack: 18.340 seconds
Total money available on server: $25.552
Required number of open ports for NUKE: 1
SSH port: Open
FTP port: Closed
SMTP port: Closed
HTTP port: Closed
SQL port: Closed
[neo-net ~/]> hack
[||||||||||||||||||||||||||||||||||||||||||||||||||]
Hack successful on 'neo-net'! Gained $0.000 and 10.500 hacking exp
Security increased on 'neo-net' from 8.002 to 8.004
[neo-net ~/]> grow
[||||||||||||||||||||||||||||||||||||||||||||||||||]
Available money on 'neo-net' grown by 0.283585%. Gained 10.500 hacking exp.
Security increased on 'neo-net' from 66.204 to 66.304
[neo-net ~/]> analyze 
Analyzing system...
[||||||||||||||||||||||||||||||||||||||||||||||||||]
neo-net: 
Organization name: Neo Nightclub Network
Root Access: YES
Can run scripts on this host: YES
RAM: 32.00GB
Backdoor: YES
Required hacking skill for hack() and backdoor: 50
Server security level: 66.304
Chance to hack: 31.01%
Time to hack: 1 minute 47.432 seconds
Total money available on server: $76.909m
Required number of open ports for NUKE: 1
SSH port: Open
FTP port: Closed
SMTP port: Closed
HTTP port: Closed
SQL port: Closed
[neo-net ~/]> 
```

So going from $25 to $76m is apparently 0.3% growth?, so that's weird.

```
[neo-net ~/]> hack
[||||||||||||||||||||||||||||||||||||||||||||||||||]
Hack successful on 'neo-net'! Gained $93.242k and 10.500 hacking exp
Security increased on 'neo-net' from 66.304 to 66.306
[neo-net ~/]> analyze 
Analyzing system...
[||||||||||||||||||||||||||||||||||||||||||||||||||]
neo-net: 
Organization name: Neo Nightclub Network
Root Access: YES
Can run scripts on this host: YES
RAM: 32.00GB
Backdoor: YES
Required hacking skill for hack() and backdoor: 50
Server security level: 66.306
Chance to hack: 31.01%
Time to hack: 1 minute 47.435 seconds
Total money available on server: $76.816m
Required number of open ports for NUKE: 1
SSH port: Open
FTP port: Closed
SMTP port: Closed
HTTP port: Closed
SQL port: Closed
[neo-net ~/]> 
```

OK, so looks like server is back to normal now.

**Comment by Snarling** [comment]
So you are not intended to empty out servers. As you noticed this would normally require infinite growth to ever recover the server (or to even reach $1). Emptying out servers, or even nearly emptying them out, is extremely inefficient and should be avoided.

If you need the API to help you to recover the server, you can see any of the documentation for [ns.growthAnalyze](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.growthanalyze.md), also explained in some other function documentation as well. There is an additive factor of $1 per thread that is added before the multiplicative growth factor. So if you're starting at $0 and using 25 threads like the terminal grow does, you will end up with $25*(growth factor) instead of staying at 0 perpetually. When the server is not essentially empty, the additive growth can just be ignored (when you are starting from a value of $1m, a factor of +$1000 is a 0.1% impact.

If you need a solution that accounts for the additive growth factor, you can use this knowledge about how additive growth works to solve it yourself, or if you need an API to tell you the exact number of threads to use to rescue an empty server, then there is the formulas API and [ns.formulas.hacking.growThreads](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.hackingformulas.growthreads.md). But basically the result is going to be you need a crazy number of threads and you shouldn't have emptied the server in the first place.

> So going from $25 to $76m is apparently 0.3% growth?, so that's weird.

Your server security went from 8 to 66 between those two `analyze` calls. You have other scripts targeting that server in the background that finished in between your `analyze` calls that are responsible for most of that growth. The terminal grow command just uses 25 threads and would not cause that level of security increase.

**Comment by Snarling** [comment]
Closing as this was just a usage issue. Documentation makes it clear that you are not intended to empty out servers, and if you do, you can rely on a $1 per thread additive rescue bonus before the multiplier is applied (which is not accounted for by growthAnalyze but you can either account for yourself or use formulas.hacking.growThreads instead). For instance the remarks on [growthAnalyze](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.growthanalyze.md) make this clear, and it is mentioned on some other related functions as well.
