### ISSUE TITLE
[Bug] Recent UI change has decohered progress bars from skill levels

### ISSUE THREAD

**Issue by Darker7** [bitburner-official/bitburner-src#465]
## The Problem
The times at which skill levels increase and at which the progress bars fill up are not the same.

This presents a gameplay problem, because…

1. it makes it impossible to judge whether I should wait 5 seconds for the next level up before switching from the high EXP activity, or if I'd just be wasting my time by waiting.
2. it makes estimating how far ahead/behind skills are relative to each other, for purposes of getting the most relevant levels for my time, require so much effort automating it would be faster than doing it once.

## Expected Behaviour
Whenever, and only when, the progress bar fills up, does the level of a skill increase.  
Multiple levels may, of course, be gained within a single UI update.

## Leads on The Cause
The obvious and likely culprit for this is the recent memoization optimisation.

## Save file in case this isn't a global problem:
[bitburnerSave_1680768282_BN11x1.txt](https://github.com/bitburner-official/bitburner-src/files/11168126/bitburnerSave_1680768282_BN11x1.txt)

**Comment by Snarling** [comment]
That section does not use memoization, the state for the skill numbers is updated at the same time as the progress bars, in response to an OverviewEventEmitter event.

If you're on the main branch, this may be fixed already on dev, I believe the issue fixed in #434 was causing some inconsistency between the bar and the skill number. Do you still have the issue at https://bitburner-official.github.io/bitburner-src/ ?

**Comment by Darker7** [comment]
~~No, it doesn't persist on the dev branch.~~

Actually, it does. I just didn't notice at first, but after installing augmentations, with the fast early progress, it became obvious again :Ü™
