### ISSUE TITLE
React errors occur when using translation extensions

### ISSUE THREAD

**Issue by Nisrineaeh** [bitburner-official/bitburner-src#527]
### How did this happen?

Please fill this information with details if relevant.

- [ ] Save file
- [ ] Minimal scripts to reproduce the issue
- [ ] Steps to reproduce

### Environment

* Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
* Page: Script Editor
* Version: v2.2.2 (d3f9554a)
* Environment: Production
* Platform: Browser
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
* Features: lang=fr-FR cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```

**Comment by d0sboots** [comment]
Any details about what you were doing at the time? Has it happened more than once?

**Comment by Snarling** [comment]
Are you using a translation extension? Those can cause this issue because they mutate the DOM in ways that React does not know about, and then React is not able to locate the correct nodes to perform its own updates.

There are some ways we can address this, it's just going to require going over most of our react code with a fine toothed comb. See https://github.com/facebook/react/issues/11538#issuecomment-1512673555 for a basic overview of what causes this issue to occur and how we can restructure our jsx to prevent these issues.

Alternatively there is also a workaround we can implement, although it can cause degraded performance and potentially hides some real errors: https://github.com/facebook/react/issues/11538#issuecomment-417504600

Also related is issue #358.

Once it's confirmed that this is due to translation services, we can close one or the other of these issues as a duplicate.
