### ISSUE TITLE
All Augmentations seem to be invalid when using `ns.grafting.getAugmentationGraftPrice()` 

### ISSUE THREAD

**Issue by Bill-GD** [bitburner-official/bitburner-src#529]
`ns.grafting.getAugmentationGraftPrice()` seems to consider all augs to be invalid even when the names are provided by the game itself. `ns.grafting.getAugmentationGraftTime()` is fine though.

- Save file
[bitburnerSave_1685069033_BN12x2.zip](https://github.com/bitburner-official/bitburner-src/files/11571154/bitburnerSave_1685069033_BN12x2.zip)

- Minimal scripts to reproduce the issue
```JS
ns.grafting.getGraftableAugmentations().forEach(aug => {
    ns.print(ns.grafting.getAugmentationGraftPrice(aug));
});
```
- Version of the game: Bitburner v2.3.0 (7f6b96fda)

**Comment by bezrodnov** [comment]
Hi! There's a missing negation operator here: https://github.com/bitburner-official/bitburner-src/blame/dev/src/NetscriptFunctions/Grafting.ts#L29 (caused by [this change](https://github.com/bitburner-official/bitburner-src/commit/ebae35b1fb118b0fb0a399d40750a166f06bc854#diff-2654d0e5652289a9c23948be08e7f9b50c737a30362b521fee6bd5373ab054a5L28))
```ts
 if (!getGraftingAvailableAugs().includes(augName) || augmentationExists(augName)) {
```
it should be
```ts
 if (!getGraftingAvailableAugs().includes(augName) || !augmentationExists(augName)) {
```
The same is used across other places in this file. Looks like a good candidate for refactoring since this block is repeated at least 3 times :)
