### ISSUE TITLE
Uncaught Promise Error

### ISSUE THREAD

**Issue by ericbrgrd** [bitburner-official/bitburner-src#541]
[bitburnerSave_1685308460_BN1x1.json.gz](https://github.com/bitburner-official/bitburner-src/files/11585894/bitburnerSave_1685308460_BN1x1.json.gz)

Havent played in a while and wanted to get back into it but anything I try to type in terminal return an uncaught promise error (ls, run, nano, etc.).
Also tried an older save with same result.
BitBurner v2.3.0

**Comment by d0sboots** [comment]
K, I can load your save and repro the issue. Looking into it now...

**Comment by d0sboots** [comment]
The root cause of this is that the game version is listed as 31 (current), but the scripts and textfiles are still arrays (unmigrated).

Do you have a backup copy of a save *before* you tried to load it on the latest version? I'd really like to see what's going on.
If you don't, that's fine too, I have a fix planned for you and other people who have somehow ended in the same situation.

**Comment by d0sboots** [comment]
OK, I have a fix for your issue, but I'm going to work on another person's loading issue that I think is related before submitting it.

**Comment by ericbrgrd** [comment]
[bitburnerSave_1647795260_BN1x0.zip](https://github.com/bitburner-official/bitburner-src/files/11588744/bitburnerSave_1647795260_BN1x0.zip)

Ok cool. I have an older backup from sometime last year just in case not sure what version it was on.
