### ISSUE TITLE
Autocompletion does not work properly with ./ command (use run instead for the time being)

### ISSUE THREAD

**Issue by brunnerh** [bitburner-official/bitburner-src#549]
I have script for killing scripts on multiple servers which takes a file name as input, this used to complete correctly in 2.2.2.

So hitting tab after something like the following would complete the name to my `basic-loop.js` file:
```
./kill-scripts.js ba
ks ba
```
(The latter just being an alias)

This is no longer the case, with or without alias.

v.2.3.0  (fd6478a5b)
Windows 10, 64 bit
Chrome 113.0.5672.127 (64-bit)
Firefox 113.0.2 (64-bit)

**Comment by Snarling** [comment]
If you change your alias from `./kill-scripts.js` to `run kill-scripts.js` it should autocomplete normally. I'll take a look at what broke the ./ use case for autocompletion.

~~Also keep in mind that ./ now takes into account the current working directory, so your alias would not work if you're in a different directory.~~

Actually that was already using relative paths. But now you can do `run /kill-scripts.js` and it will treat it as an absolute path due to the leading slash.

Will include a fix for this in 2.3.1. Since `run` still works normally it's not super high priority.

**Comment by brunnerh** [comment]
Just to be clear, the script itself completes just fine, this is about the completion of *arguments* which are script or other file names.
(And using `run` does not change that.)
