### ISSUE TITLE
Detect shared ns instance.

### ISSUE THREAD

**Issue by TheMas3212** [bitburner-official/bitburner-src#58]
[hydroflame]
https://www.reddit.com/r/Bitburner/comments/u2w39s/getting_concurrent_calls_error_but_im_using_await/

This user was sharing his ns instance globally, causing him to have issues when running the same script multiple times.

It should be possible to detect that when there's concurrent calls that the originating scripts are from different scripts and give a more helpful error message.

**Comment by Snarling** [comment]
When the error is originally created, it is given a header based on the ns instance that caused the error, since the ctx is used there.

When the error is caught in the lifecycle of the script that actually errors out, it should be able to detect that the header already attached does not match the current script. So we could detect that an error was generated from a shared ns instance. I'm not sure what it should communicate with the player at that point though.

I think if a player is doing advanced stuff like sharing ns instances globally between different scripts, it's kind of up to the player to troubleshoot issues like this, IMO not worth complicating the error lifecycle in order to give more specific errors in this particular usecase.
