### ISSUE TITLE
Contract "find all valid math expressions" rejects all results

### ISSUE THREAD

**Issue by FatEarthler** [bitburner-official/bitburner-src#580]
Description:
 - I have a script which reliably solved "Find All Valid Math Expressions" pre 2.3.0 (see attached favme.js, credit goes to https://www.reddit.com/r/Bitburner/comments/rzh8e8/iterative_solution_to_find_all_valid_math/)
 - This same scripts solutions are not longer accepted since 2.3.0
 - On a very small example (which I have no longer at hand, unfortunately), I could manually verify the solution of favme.js as correct, yet the solution was not accepted by bitbuner 2.3.0

Affected Version: Bitburner v2.3.0 (fd6478a5b)

Thanks for any help provided.

Attachments:
 - Savegame [bitburnerSave_1686124372_BN1x3.zip](https://github.com/bitburner-official/bitburner-src/files/11674250/bitburnerSave_1686124372_BN1x3.zip)
 - favme.js [favme.zip](https://github.com/bitburner-official/bitburner-src/files/11674248/favme.zip)
 - textfile w/ example [favme example.txt](https://github.com/bitburner-official/bitburner-src/files/11674253/favme.example.txt)

[favme example.txt](https://github.com/bitburner-official/bitburner-src/files/11674253/favme.example.txt)
[favme.zip](https://github.com/bitburner-official/bitburner-src/files/11674248/favme.zip)
[bitburnerSave_1686124372_BN1x3.zip](https://github.com/bitburner-official/bitburner-src/files/11674250/bitburnerSave_1686124372_BN1x3.zip)

Thanks for any help provided.

**Comment by Snarling** [comment]
Prior to 2.3, there was a bug that allowed you to submit answers with extra incorrect solutions, as long as your array contained all the right solutions. Now providing incorrect solutions fails the contract like it is supposed to.

Your solution included 65 answers that were invalid. The invalid solutions you provided are all the solutions starting with -, which is not valid. The operators +-* can only be inserted between numbers, not at the beginning of the string.

For instance if negative starting numbers were allowed, one of the examples would be wrong:
```
Input: digits = "105", target = 5
Output: [1*0+5, 10-5]
```
since -1*0+5 would be valid as well if negative starting numbers were allowed.
