### ISSUE TITLE
cancelExportMaterial prototype mismatch

### ISSUE THREAD

**Issue by mathaefele** [bitburner-official/bitburner-src#582]
-  Version of the game, e.g. Bitburner v2.3.0 (Steam as of June 7 2023) 
- 
In the documentation the prototype is `cancelExportMaterial(sourceDivision, sourceCity, targetDivision, targetCity, materialName)`. It sounds nice and usable. However, when executing it, the game complains:
```
corporation.cancelExportMaterial: amt expected to be a string. Is undefined.
```

I guess it is waiting for the amount as a last parameter, like the `exportMaterial` function. But as there is no API to get all exports already in place, it is hard to keep/reconstruct this info. 

So it would be nice if the game could follow the documentation !!

Thanks a lot

**Comment by kateract** [comment]
@mathaefele There is an API for exports, just a little tricky to get to: ns.corporation.getMaterial(divisionName, cityName, materialName).exports

**Comment by Snarling** [comment]
For the release version of the game, you should be selecting the "stable" branch instead of "dev" branch when viewing the markdown files:
https://github.com/bitburner-official/bitburner-src/blob/stable/markdown/bitburner.warehouseapi.cancelexportmaterial.md

Removing amt from the function signature (and actual requirements of the function) is only live on the development version right now (specifically https://bitburner-official.github.io/bitburner-src/)

**Comment by Snarling** [comment]
2.3.1 is released now on Steam FYI, you should be able to omit the amount when canceling exports now.

**Comment by mathaefele** [comment]
Ok thanks for the notice about the dev / stable version of the doc. I started the game a few months ago and I actually discovered this bitburner-official repo with the doc today !! I was using https://github.com/danielyxie/bitburner/ until now...

Indeed, the API has been updated in 2.3.1 and it works like a charm :smile: 

Thanks a lot guys for this outstanding game :+1:
