### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getCost') (at "Sleeves")

### ISSUE THREAD

**Issue by AssenD** [bitburner-official/bitburner-src#591]
### How did this happen?

Clicked on sleeve button "Manage Augmentations". The sleeve had them all, but I clicked it.
Other two buttons still work.

### Environment

* Error: TypeError: Cannot read properties of undefined (reading 'getCost')
* Page: Sleeves
* Version: v2.3.1 (100030008)
* Environment: Production
* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/2.3.1 Chrome/108.0.5359.215 Electron/22.2.1 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
```
Copy your save here if possible
```
[RECOVERY_BITBURNER_1686421962.json.log](https://github.com/bitburner-official/bitburner-src/files/11713077/RECOVERY_BITBURNER_1686421962.json.log)

**Comment by Snarling** [comment]
I'm not sure how, but instead of the `Z.O.Ë.` aug you have an aug named this on your sleeve:
![image](https://github.com/bitburner-official/bitburner-src/assets/84951833/5374ea3e-9750-4686-84bf-3f7743875317)

Because that's not the name of an actual aug, the game throws an error there when looking up its information while trying to display your owned augs.

I could not reproduce the issue on a fresh save. When I bought the aug, it still has the normal name. I can add a workaround for this crash though, where the game will just skip displaying an aug that is not real, instead of erroring out. But I would like to know how your sleeve thinks it owns an aug with an invalid name.

**Comment by d0sboots** [comment]
That's some mojibake due to Unicode encode/decode issues. It's possible it was the game, but IMO it's more likely it happened during manual save-game editing (maybe trying for the one acheivement)?

**Comment by AssenD** [comment]
> That's some mojibake due to Unicode encode/decode issues. It's possible it was the game, but IMO it's more likely it happened during manual save-game editing (maybe trying for the one acheivement)?

Quite right! 
But still, the game shouldn't crash ;)

**Comment by Snarling** [comment]
If you put invalid data into your save, there is no guarantee that you won't cause the game to crash. It's your job to not mess your save up when you're editing it.
