### ISSUE TITLE
ns.getSharePower needs clearer information about what it returns.

### ISSUE THREAD

**Issue by Noxebo** [bitburner-official/bitburner-src#607]
[link](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.ns.getsharepower.md)

All a new player gets is "number".

Knowing it's a percentile/multiplier of your current reputation gain would be infinitely more helpful.

**Comment by d0sboots** [comment]
Yeah, the docs on this one are a bit... sparse XD

**Comment by myCatsName** [comment]
`ns.getSharePower`
current definition:
 `Calculate your share power. Based on all the active share calls.`

proposed update:
 `Share Power has a multiplicative effect on rep/second while doing work for a faction.`
`Share Power increases incrementally for every thread of share running on your server network, but at a sharply decreasing rate.`


And because it is common confusion, I would also consider to update the definition for `ns.share()`
current:
`Increases your rep gain of all faction work types while share is called.`
   `Scales with thread count.`

propose adding "Each cycle of ns.share() is 10 seconds.":
`Increases rep/second for all faction work while share is running.
   Each cycle of ns.share() is 10 seconds.
   Scales with thread count.`

notes:
 not sure about capitalization in Share Power
  not sure if "is running" is equal to "is called", but "is called" made me think possibly "at time of execution" rather than "while executing".
 `rep/second` should be more clear than `rep gain` 

links to  #606
