### ISSUE TITLE
Sanitize Parentheses coding contract appears to reject answers with spaces inbetween array string elements

### ISSUE THREAD

**Issue by echo-bravo-yahoo** [bitburner-official/bitburner-src#616]
In Bitburner 2.3.1, coding contracts for "Sanitize Parentheses in Expression" will reject answers like:
```
["()a", "(a)"]
```

But accept answers like:
```
["()a","(a)"]
```

This is doubly confusing because the example answers have spaces:
```
IMPORTANT: The string may contain letters, not just parentheses. Examples:
"()())()" -> ["()()()", "(())()"]
"(a)())()" -> ["(a)()()", "(a())()"]
")(" -> [""]
```

Answers should be accepted even with spaces between the strings.

**Comment by ABruel** [comment]
You are correct in saying the examples should reflect valid answers, and currently they don't. 

The game does sanitize inputs and does remove spaces, but it removes spaces only after removing quotes from the start of the string. So this results in your answer being sanitized to an array `["()a", '"(a)']` (notice the `"` at the start of the second string).

> Answers should be accepted even with spaces between the strings.

That depends on what the design intentions are. One could argue that the correct answer **must** have spaces after the commas, since the examples have them. 

One could also argue that the strings must be double quoted, or that they must the quoted the same at the end as they are at the start.

Currently, `["(a)()()',"(a())()']` is a valid answer. As is `[` for the last example (empty would also work, but the game checks for empty string before checking if it is a valid solution). In fact, you don't even need `[` at the start or end, you don't even need quotes. `(a)()(),(a())()` is valid.

**Comment by myCatsName** [comment]
I think I have found the [source of this bug](https://github.com/bitburner-official/bitburner-src/blob/ae8f26f03bfa8d58b73460f32c346fb2e6e7d989/src/data/codingcontracttypes.ts#L40), and agree answers should be accepted with a space before each array element. The examples given to the player were updated last year, but I don't think they match the sanitizing process strictly. You can see in the update, the examples include space while the solution has no spaces https://github.com/bitburner-official/bitburner-src/pull/389. 

Currently: Each array element has quotes removed, then removes whitespace.

`      for (let i = 0; i < sanitizedPlayerAnsArr.length; ++i) {`
       ` sanitizedPlayerAnsArr[i] = removeQuotesFromString(sanitizedPlayerAnsArr[i]).replace(/\s/g, "");
      }`


The "bug" (I think) is because removeQuotesFromString is strictly removing single and double quotes, and could easily be updated to a regex allowing a single space optional before the quote. This function appears to only be used in Sanitize Parentheses cct and Find Valid Math Expressions cct and is defined in a CCT file. 

`function removeQuotesFromString(str: string): string {`
  `let strCpy: string = str;
  if (strCpy.startsWith('"') || strCpy.startsWith("'")) {
    strCpy = strCpy.slice(1);
  }
`
`
  if (strCpy.endsWith('"') || strCpy.endsWith("'")) {
    strCpy = strCpy.slice(0, -1);
  }
  return strCpy;
}
`

I can work on re-writing or updating to test, but I think there are multiple ways to fix, and would ask input from whomever wrote the function or devs.
