### ISSUE TITLE
Suggestion: TIX API cycle length functions

### ISSUE THREAD

**Issue by amuck-gorilla** [bitburner-official/bitburner-src#638]
# Suggestion

Add a function to the `TIX` API of the form `getTimeUntilUpdate()`, which returns the amount of time in milliseconds until the stock market updates. Another possible function is `getUpdateCycleLength()`, which returns the current amount of time between market updates, equivalent to the length of time between the last update and the next scheduled one. The function names might need fine-tuned to avoid ambiguity between ticks, cycles, and updates.

# The problem

I'm currently running an auto-trader which, after it buys and sells, sleeps for 6000 milliseconds to give enough time for the next update. However, when there's accumulated offline time, the market updates every 4 seconds instead of 6, but there's no easy way for a script to detect this. Implementing either of these two solutions would solve this problem by allowing `ns.sleep(ns.stock.getTimeUntilUpdate());`, a clean and elegant solution.

**Comment by d0sboots** [comment]
This has been suggested many times before. There's two problems with it:
1. It's impossible to actually implement, since we don't know how long the tick will be (in all cases) until it happens.
2. It's a noob trap. If it existed, people would sleep that long thinking it would keep them synced to the stock market, and due to how sleeping works in JS it *would not*.

Instead, you should sleep for less time than the cycle ( 1 second, say) and check if a stock's price has changed. If it hasn't, the market hasn't ticked yet. Note that there is no reason/benefit to acting right at the beginning of the tick.

**Comment by d0sboots** [comment]
Oops, meant to close.

**Comment by amuck-gorilla** [comment]
> This has been suggested many times before.

My apologies, I searched issues and PR requests but found nothing on this topic. I guess that now this issue will show up for anyone in the future who checks.

> 1. It's impossible to actually implement, since we don't know how long the tick will be (in all cases) until it happens.

Couldn't you check if there was enough saved cycles from offline time for a 4 second update, if so, return 4000, if not, return 6000? It seems doable, at least to me, and while I can now clearly see `getTimeUntilUpdate` being a noob trap like you said, but `getUpdate(Cycle)Length`/`getCurrentUpdate(Cycle)Length` doesn't seem so bad, though I might be missing something.

Thank you for providing feedback, and especially for doing it so promptly. I hope I'm not coming across as argumentative.

**Comment by d0sboots** [comment]
> My apologies, I searched issues and PR requests but found nothing on this topic. I guess that now this issue will show up for anyone in the future who checks.

Yeah, it's been suggested on Discord. It's good that you made this issue, since it will provide a searchable/linkable record for the rationale. Sorry, I didn't mean to imply you hadn't done due diligence.

> Couldn't you check if there was enough saved cycles from offline time for a 4 second update, if so, return 4000, if not, return 6000?

That would work for the common cases, but it fails on the edge cases. The most obvious one is when you have 1 second of saved cycles after a market tick: then the next cycle will be **5** seconds later.

The less obvious factor comes from the fact that **the engine does not know how much time has elapsed until the sleep is over**. Time accumulation is based on real time: if there's a particularly long pause, it might take **7** seconds for the next market tick (and 5 for the one after that, since now there's bonus time.)

**Comment by amuck-gorilla** [comment]
> Yeah, it's been suggested on Discord. It's good that you made this issue, since it will provide a searchable/linkable record for the rationale. Sorry, I didn't mean to imply you hadn't done due diligence.

I'm not on Discord, which would explain why I didn't see it. I didn't see you as having suggested anything, I was mostly surprised because I hadn't seen anything when I searched.

> That would work for the common cases, but it fails on the edge cases. The most obvious one is when you have 1 second of saved cycles after a market tick: then the next cycle will be **5** seconds later.
> 
> The less obvious factor comes from the fact that **the engine does not know how much time has elapsed until the sleep is over**. Time accumulation is based on real time: if there's a particularly long pause, it might take **7** seconds for the next market tick (and 5 for the one after that, since now there's bonus time.)

That does seem sufficiently complicated. Maybe I'll try to solve it one day once I understand the code better, but I definitely agree with you closing the issue.
