### ISSUE TITLE
Consider adding this vite + React example to the bitburner-offical org?

### ISSUE THREAD

**Issue by paulcdejean** [bitburner-official/bitburner-src#662]
The typescript template is cool and all, but this expands on it with the power of Vite.

https://github.com/paulcdejean/vite-template

I think this could be a good boilerplate for people who want to do more advanced work in the game.

![image](https://github.com/bitburner-official/bitburner-src/assets/1987879/e0898de7-c3cc-4605-b962-08a19ce49a57)

**Comment by brunnerh** [comment]
Personally, I think React components are too powerful and maybe should not be supported at all.
Having a full UI rather than just a CLI changes the game completely.

**Comment by d0sboots** [comment]
> Having a full UI rather than just a CLI changes the game completely.

Why? The game already has UI beyond just the CLI, it's by no means a text-based game. And if you feel like custom UI is hurting your experience, you are free to not use it.

**Comment by brunnerh** [comment]
The UI that exists is very limited and the goal for the player is to automate things via scripts to be more efficient.
Being able to replace the given UI with a better UI means you do not have to implement "proper" algorithms, as everything can be steered manually.

I personally do not use it, but "just don't use it" is not a good argument in game design. Players will often readily destroy the intended -and thus sometimes their own- experience if given the chance, e.g. by grinding XP rather than learning how battle systems work.

**Comment by d0sboots** [comment]
I think you have a very different idea of both the purpose of a UI, and this game.

The purpose of this game is to have fun. If you have fun by manually controlling everything, knock yourself out. It's *already* intended that you can beat things playing manually, but it won't be as fast as if you script them.

Personally, I find using React and developing good UIs *much* harder than implementing algorithms, so the idea that folks would somehow bypass scripting by making elaborate UIs seems laughable (to me). Anecdotal evidence from the Discord also bears this out (there are lots of people scripting, very few making UIs of any kind)

**Comment by brunnerh** [comment]
If you already have experience building UIs the opposite is the case, though the fact that you have to use React creates a considerable (unnecessary?) barrier.

If I had a function that just allowed adding regular DOM elements, that would make many things *so* much easier. Instead of having to come up with elaborate ways of cross-script communication or complete automation, certain low-frequency tasks that require consideration could just be triggered by a regular button. The UI also does not have to elaborate or "good" by any stretch, just functional.

In the end this is just a design decision, which can move the challenge from one area to another. If building *interactive* UIs is being considered a valid approach that is fine by me, but having one undocumented function for it which is limited to React does not look like that to me.

**Comment by d0sboots** [comment]
You can add regular DOM elements with React.

You're free to make a UI for triggering whatever you want, but it will need to be run by a script that keeps running (and thus keeps using RAM) in order to function. I'm not sure how this "completely changes the game" vs having utility scripts that you run to do the exact same thing (manually).

**Comment by brunnerh** [comment]
> You can add regular DOM elements with React.

I am aware, the point is that React makes it much more complicated as it requires knowledge about how React works and either compilation from JSX or manual use of virtual DOM functions. You also need to somehow load a runtime to execute the VDOM reconciliation (or at least the VDOM creation functions).

Hence it would be much easier to just have a function that adds regular elements that can be directly created e.g. via `document.createElement`.

> I'm not sure how this "completely changes the game" vs having utility scripts that you run to do the exact same thing (manually).

It allows one to easily change the behavior of a running script without stopping it and changing the arguments or using cross-script communication via e.g. ports.

**Comment by d0sboots** [comment]
> Hence it would be much easier to just have a function that adds regular elements that can be directly created e.g. via `document.createElement`

`React.createElement("div", {}, "I'm some text in a node")` creates a regular div. It's not much harder. (Where it *gets* harder is if you want to reuse the styles from the game, but that would be even more true with direct use of `document.createElement`)

> It allows one to easily change the behavior of a running script without stopping it and changing the arguments or using cross-script communication via e.g. ports.

But this is not something that everyone needs or wants; it's specific to a certain style/mindset in coding. Plenty of people get by perfectly fine with scripts that perform a task and then exit.

There are also a multitude of simple ways to control a running script that are simpler than a UI, or ports: You can poll data from a file, or you can use global variables. I'm sure there are others.

There is a reasonably high bar for removing things from a game, because people (understandably) get grumpy when you do it. You have to demonstrate that the feature is *actively* bad. I don't think you've met that bar even hypothetically, but also current usage does not agree with your fears.

**Comment by d0sboots** [comment]
Replying to the original requester, since this went rather far afield:

> I think this could be a good boilerplate for people who want to do more advanced work in the game.

I agree! You should share it on #project-showcase on Discord, and/or on Reddit.
