### ISSUE TITLE
Add virtual bitburner module to make `ns` available without `main`

### ISSUE THREAD

**Issue by brunnerh** [bitburner-official/bitburner-src#677]
Right now functions in reusable modules that require access to the API need to be passed `ns` or parts of the API as argument.
It would be nice if the API could just be imported anywhere as a module.

E.g. something like:

```js
import * as ns from 'bitburner';
import { singularity, sleeve, getPlayer } from 'bitburner';
```

**Comment by d0sboots** [comment]
This will not/cannot happen, because of the state that `ns` carries. In a very real sense, it is the `ns` object that *is* "the script", not whatever code you have in the .js file.

Dealing with stateful objects like this is a standard thing, with standard solutions. One that you've already found is a calling convention where you pass the object as an arg in the same position. Another is to create classes that encapsulate your state (as appropriate); `ns` would then becomes part of that state.
