### ISSUE TITLE
Write  singularity.getAugmentationFactions()

### ISSUE THREAD

**Issue by myCatsName** [bitburner-official/bitburner-src#705]
singularity.getAugmentationFactions() method based on discord chat with hydroflame

based on getAugmentationFactions(augName: string): string[]

I have src branched on VS code, currently learning how the .ts is written

**Comment by d0sboots** [comment]
I didn't see the discussion on Discord (yet), but I'm adding my continuing opinion that information-gathering functions should not be locked behind SF4, especially stuff that can be looked up on the source. (IMO sing should be for automating *actions*.)

**Comment by hydroflame** [comment]
I can see d0tboots point but similar functions are already there. So until we API break I think it's fine to put this one there too.

**Comment by d0sboots** [comment]
The difference is that this is a new function, so it doesn't require an API break to get it right. If, in fact, you think having it outside singularity is the right thing to do.

Part of the issue is that the namespacing is *heavily* tied to SF mechanics. Something like this (and a lot of other information-granting functions) doesn't belong at the top level, because that makes things too confusing and crowded, but we don't have a grouping for stuff lot this, so a lot of it has ended up in sing, or formulas.
