### ISSUE TITLE
Lack of formulas documentation on RTD

### ISSUE THREAD

**Issue by Column01** [bitburner-official/bitburner-src#726]
I'm not sure if I'm missing something but the RTD page seems to lack a section about the formulas API (and possible others like the stock market API)

Is this intended because the docs links to the full documentation on github on the side bar? If so, I've experience numerous times where I went to look at a document following a link on the RTD only to get a 404 because the repo was moved from `bitburner` to `bitburner-src` at some point (but now that I've said this, I seem to be unable to find an example).

Some clarification would be nice

**Comment by rayanth** [comment]
As of 2.4.0 (per 2.4.0 patch notes) ReadTheDocs is deprecated as everything was moved into the documentation section of the game itself. 

Removing ReadTheDocs entirely is a work in progress, but that documentation (and in turn, now the documentation in-game) never had all of the API's - just the stuff you'd need to get a good start. 

For the advanced API's such as Formulas and Stockmarket, the documentation is currently only here in the git repository, https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/

For example, [This](https://github.com/bitburner-official/bitburner-src/blob/dev/markdown/bitburner.formulas.md) is the starting point for the Formulas API; Stock market is spread across various different doc pages, due to the various different ways you can interact with it (With TIX, without TIX, etc)
