### ISSUE TITLE
Replace for-loop updating HacknetServer maxRam with non-loop alternative

### ISSUE THREAD

**Issue by elidoran** [bitburner-official/bitburner-src#749]
The below referenced function `upgradeRam` for Hacknet has a for-loop updating the maxRam via repeatedly multiplying by two. That could be replaced with either of the two options below which don't require a loop.

```js
// 1. use Math for power of two
this.maxRam *= Math.pow(2, levels);

// 2. use a bit-shift to do the same.
this.maxRam <<= levels;
```

https://github.com/bitburner-official/bitburner-src/blob/aaaa980d10f71dab501241b043e3e1c44b1c376d/src/Hacknet/HacknetServer.ts#L106-L114

**Comment by d0sboots** [comment]
Seems like a good first PR. :)

**Comment by myCatsName** [comment]
But why? It's functionally same and causes no problem today, right?

**Comment by d0sboots** [comment]
It's a little gross to do a loop when you utterly don't need one, but I'd say changing it is the lowest of low priorities. Thus, it'll likely only get changed if the requester does it.

**Comment by myCatsName** [comment]
I think it's bad form to encourage needless semantic changes, or impose style where no formal guideline (or problem) exist. It's not an issue and could be closed. Replacing simple multiplication with a bitwise operator is worse for readability. Replacing it with  *=Math.pow(2,levels) is semantics. Sorry. Or sure, change it and make a first PR, but it's not a task for someone else.

**Comment by elidoran** [comment]
@d0sboots  I'd be happy to throw up a PR. It's an easy one, for sure. Need to know which variation to use. I assume Math.pow(), but, I'd rather have some confirmation from someone.

```js
// A. Math.pow() as is used elsewhere in the codebase:
this.maxRam *= Math.pow(2, levels);

// B. same thing with power operator instead of Math.pow():
this.maxRam *= 2 ** levels;

// C. bit-shift:
this.maxRam <<= levels;
```

@myCatsName I hear you. All too often someone makes a lot of demands without being willing to write code, as well as wanting to change the code to conform to their own preferences.

This, isn't that.

I'm happy to write some PR's.  I prefer to post an Issue before writing a PR in order to have a discussion about whether to even do a PR and what would go in it.  

I'd like you to take a second look at this. And, you too, @x3cion, I see ur thumbs up.  I'll put both the original code and my replacement below here in a block to look at them side-by-side.

```js
// current:
for (let i = 0; i < levels; ++i) {
  this.maxRam *= 2;
}

// replacement:
this.maxRam *= Math.pow(2, levels);
```

When it's a matter of style or preference there are proponents of both ways of doing it. Who's promoting converting the lower version to the upper version? I think no one looks at that math operation and says, "I think this would be better as a loop."

It's also not "semantics", which I take to mean "it's the same thing in a different way", because they do different work. The replacement eliminates the looping entirely. A "semantics" thing would be suggesting replacing a Math.pow() operation with the use of the `**` operator. That would be something to politely decline.

As a final note, the bit-shift operation is the only one which produces the correct result with one operation. The other two versions perform exponentiation and then a multiplication.

**Comment by myCatsName** [comment]
I don't want to encourage time wasting or "hand waving". If you imagine there is a difference in performance, or a need to eliminate the 2 lines needed for the existing loop, assuredly neither are true.

**Comment by d0sboots** [comment]
> I'm happy to write some PR's. I prefer to post an Issue before writing a PR in order to have a discussion about whether to even do a PR and what would go in it.

We generally aren't that formal here for bikeshed stuff like this. Go ahead and pick your favorite and send a PR.

**Comment by d0sboots** [comment]
> I don't want to encourage time wasting or "hand waving".

This is a classic bikeshed argument. More collective time has been spent talking about whether it's worth changing than it would take to just change it. XD That's why IMO the best thing is to just send a PR, and then the only time being spent is the author's (who can do what they want with their time), and Snarling who only needs a few minutes to accept or reject a change this small.

**Comment by myCatsName** [comment]
>More collective time has been spent talking about whether it's worth changing than it would take to just change it.

You should have closed it.

**Comment by d0sboots** [comment]
> You should have closed it.

If the author was not going to do the work, I would have. If (as I suspected, and turned out to be the case) they were filling an issue prior to opening a PR, the issue will get closed when the PR does.

**Comment by myCatsName** [comment]
"Curly braces review" would be the term for this.

Eli has hundreds of repos, I didn't think he needed a soft pitch PR. Rather the education that this is bad code review could be valuable, instead he's been encouraged to change good code, and reinforced a fear of for loops. He still thinks a bitwise operator is an improvement because it's only 1 operation. It's not good. I will unsubscribe now.

**Comment by s-venter** [comment]
Bit shifting signed values has its own complications. No need to bit shift if your focus is not on individual bits. The processor is capable of doing multiplication just as efficient.

**Comment by elidoran** [comment]
@s-venter I wouldn't say its efficiency is a factor though, you're right the JIT will change all the power-of-two operations to bit-shifts and so they'll have the same efficiency; it'll also do bit-shifts with many "divide by a constant" operations. I like it because it's the simplest form to produce the desired result and it's easy to reason about. There's no reason to be afraid of doing a bit-shift. Just like everything else it requires some understanding and care. They already wrote in code checks to ensure the value [is a non-negative integer](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Hacknet/HacknetHelpers.tsx#L265-L267) and isn't large enough to [exceed the limit](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Hacknet/HacknetHelpers.tsx#L282) set for HacknetServer's [max ram](https://github.com/bitburner-official/bitburner-src/blob/dev/src/Hacknet/data/Constants.ts#L49) (8192).

If they ever raise the limit from the current `2 ** 13` to above `2 ** 32` then it would become an issue. I think it's unlikely the HacknetServer will ever have a max ram above 4_294_967_296, when it's currently maxed at 8192. So the `levels` is limited to a value from zero to 13 and is capped in relation to the current maxRam value it'll be altering. I'd say they were quite careful to ensure it is an acceptable value before it ever reaches the upgradeRam function.

Finally, I didn't change it to a bit-shift. I merely think it's appropriate to document available options in case someone has a reason to favor one or see it as an opportunity to change something.  And, ya never know, someone may read it and find it intersting for some reason.

In this case, I chose the Math.pow() because that's used elsewhere in the code, including the value check I referred to above, and the other options are not. Consistency.

**Comment by s-venter** [comment]
2 ** 31 - 1

**Comment by x3cion** [comment]
Since I got tagged, here's my two cents: The for-loop is perfectly valid and working code. It is descriptive and every developer, even new to coding or at least new to the code will understand it simply from the structure, without a comment. It simply has no real flaws that need to be solved.

So this is more about preference and that's not a good argument. Imo, for decisions like that and to even allow such PR's at all, a coding standards definition must exist in the first place, defining if this code is somehow wrong, because then everyone would've agreed on this coding standard definition. If it doesn't, the change is not relevant enough to be made.

Since I'm a no-one here, please do me a favor and if you really replace one good solution with another good solution (talking about `Math.pow`, bitshifting is just clever code, which is bad), explain it via comment, so it's down to the same level of simplicity.

**Comment by myCatsName** [comment]
Examples of bad code review - changing good code, and using code review as a place to debate style.

These are bad habits being pushed as good practice. 

Notice d0s ignored Eli's idea for a UI enhancement, dismissed the issue about stock mechanics as no one particularly "cares" and it's a "useless" mechanic, but has been the biggest defender of this nonsense. His pedantry is spilling over and encouraging bad habits, causing a rift. 

Eli you are learning to waste time and double down.

>There's no reason to be afraid of doing a bit-shift.

You don't want to learn a lesson about readability and being kind to future readers, you want to defend and debate. Done, done and done.

**Comment by Snarling** [comment]
Yeah it really is an unnecessary / frivolous change. But I went ahead and merged it because it's still just as understandable with Math.pow and now is more concise. But really it is not something a PR should have been made for and I suggest not opening up PRs for similarly frivolous changes in the future.

Bit shifting would have been a bad change, despite being probably more efficient. It's not as straightforward and there are a lot of caveats for bit shifting. As mentioned in a comment above, the constraints for this particular function mean that it would have been fine to use bit shifting, but it's just less readable code for the average contributor. So unless it provides a significant performance advantage in a place that actually needs a performance boost, it's a frivolous change that also makes the code more arcane.
