### ISSUE TITLE
Sleeves on Bladeburner Training reduce stamina to below 0

### ISSUE THREAD

**Issue by n1gh7sh1f7** [bitburner-official/bitburner-src#844]
Hi, 

Just launched the game after the 2.5.0 update and set my sleeves to work Bladeburner Training after reading that the action has become available with the update.

After a few minutes i went into Bladeburner to set some task for the main sleeve and stamina was in the neighborhood of -80, making any Bladeburner actions impossible.

No scripts, just manual interaction with the sleeves and Bladeburner screen.

Is this intended behavior? Should sleeves consume stamina for Training actions? If they should, should stamina go below 0 at all?

Bitburner v2.5.0 (c32957eda)

Thank you.

**Comment by Snarling** [comment]
Seems like this is due to lots of bonus time being used to aggressively perform the training action faster than you can recuperate the stamina drain.

It is intended to cost stamina, and outside of bonus time (or the player draining all the stamina on much more stamina-intensive tasks) that should be less of an issue. You'd be able to go negative on stamina with just the player if you could do the training action super fast like an army of bonus time sleeves can.

As far as negative stamina I'm not sure what the right answer is here. I think if we implemented a hard minimum stamina of 0, then we would have to have the sleeves fail to perform the task if they finish the task with not enough stamina, and I think the time waste on those sleeves would feel a lot worse than temporarily having negative stamina.

**Comment by n1gh7sh1f7** [comment]
Understood, thank you for the reply.
