### ISSUE TITLE
additionalMsec delay overflow

### ISSUE THREAD

**Issue by nanogyth** [bitburner-official/bitburner-src#940]
https://discord.com/channels/415207508303544321/415213413745164318/1176573161727340625

https://github.com/bitburner-official/bitburner-src/blob/6a76e1a9ab58d9b6f103c90793307c61a668334f/src/Netscript/NetscriptHelpers.tsx#L379

setTimeout ends immediately for numbers >= 2**31

**Comment by nanogyth** [comment]
https://discord.com/channels/415207508303544321/415213413745164318/1123211082681565225

**Comment by d0sboots** [comment]
Additional (non-discord) context, since the context here is terse: It's not additionalMsec itself that is overflowing, but rather the underlying call to setTimeout, which uses signed 32-bit integer math for historical reasons that are now set in stone. (https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value)

It would be reasonable for us to error on calls to H/G/W if the calculated time becomes implausibly large.
