### ISSUE TITLE
TypeError: String is not a function (at "Terminal")

### ISSUE THREAD

**Issue by vbatecan** [bitburner-official/bitburner-src#959]
### How did this happen?

Well... I made an error in my script. It was like this
```
host: String = "foodnstuff"; // ERROR!
ns.getServerBaseSecurity(host);
currentSecurity -= ns.weaken(host);
console.log("Server weakened!: " + currentSecurity);
```
host: String made an error.

### Environment

* Error: TypeError: String is not a function
* Page: Terminal
* Version: v2.5.1 (0c2997d32)
* Environment: Production

* Platform: Steam
* UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) bitburner/2.5.1 Chrome/116.0.5845.228 Electron/26.3.0 Safari/537.36
* Features: lang=en-US cookiesEnabled=true doNotTrack=null indexedDb=true
* Source: n/a

### Save
[RECOVERY_BITBURNER_1701610333.json](https://github.com/bitburner-official/bitburner-src/files/13539092/RECOVERY_BITBURNER_1701610333.json)

**Comment by d0sboots** [comment]
Just to be clear: Are you saying you made a bad script, and the game errored to the recovery screen?

**Comment by vbatecan** [comment]
> Just to be clear: Are you saying you made a bad script, and the game errored to the recovery screen?

Yes, that's what happened. Good thing that I just started playing (just finished the tutorial and hacked foodnstuff), I deleted the save file.

**Comment by d0sboots** [comment]
I can reproduce this with the attached save, so this is serious. Thanks for reporting!

**Comment by d0sboots** [comment]
Oh dear, looking into this a bit more, I see what happened, and I'm not sure if there's a way to guard against it. This is despite the fact that the game shouldn't crash from doing what you did. XD

The line `host: String = "foodnstuff";` is **not** actually a syntax error. `host:` defines a *label* for the statement, suffice to say it's not something that you usually need but it's not invalid. The rest assigns the value `"foodnstuff"` to the global variable `String`.

The problem is that there is *already* a global variable `String`, and it's very important: It is the function that creates strings! For instance, `String(5)` turns the number 5 into the string "5". By replacing it, suddenly everywhere that expects to be using that function is getting a string (which can't be used as a function), and throwing an error. And this includes *the error-handling code itself*.

A basic principle of how BitBurner works is that user scripts are intentionally running as part of the same JS environment as the game - they are not sandboxed away. This means you can use techniques just like this to do sneaky things to the game, like creating exploits, and this is known/semi-encouraged. `String` is used so ubiquitously that I'm not sure we can guard against this, even for accidental usage.

**Comment by Snarling** [comment]
We can protect String from being modified by doing something like this:

```js
Object.defineProperty(window, "String", { writable: false, configurable: false });
```

~~However I'm not a huge fan of that.~~ In general I'm not a huge fan of this type of protection, but it might be a good idea in this case due to the likelihood of someone making a mistake like the OP while trying to write typescript-esque code.

**Comment by Snarling** [comment]
Actually, just `{ writable: false }` is good enough to prevent reassigning inadvertently, and if a player knows that they are doing and wants to declare it as writable again they are free to do so.
