### ISSUE TITLE
RegExp.exec has RAM cost of NS.exec

### ISSUE THREAD

**Issue by AugSphere** [bitburner-official/bitburner-src#973]
RegExp.exec seems to require as much memory as NS.exec.

Minimal example:
```js
/** @param {NS} ns */
export async function main(ns) {
  /./.exec("");
}
```
Memory requirement can be seen in `mem` output:
```
This script requires 2.90GB of RAM to run for 1 thread(s)
  1.60GB | baseCost (misc)
  1.30GB | exec (fn)
```
Version: 2.5.1

**Comment by d0sboots** [comment]
This is a perennial issue with how the static RAM analysis works. It is relatively simple, and isn't smart enough to tell what type of object the function is called on (so it can't tell the difference between `regex.exec` and `ns.exec`. Indeed, without context, there *is* no difference - you could have assigned `ns` to a variable called `regex`, which is why this is a hard problem (and in the general case, unsolvable).

To get around your actual issue, there are a couple of ways:
* You can write it as `/./["exec"]("");`. Clunky, but it works to avoid the static RAM analysis.
* You can use `ramOverride` when running the script. This lets you set *any* desired RAM amount you want when running the script, however the dynamic RAM check still applies, meaning if you call more NS functions than you have allocated RAM for your script will be killed. (The static RAM check normally prevents this.) However, this is only an option to `run()` and `exec()`, meaning it doesn't work from the commandline.

**Comment by AugSphere** [comment]
`ramOverride` should be simple enough to use, thanks for the tip!

Still feels like there should be a reasonably straightforward way to at least catch unambiguous cases like `.exec` being called directly on a regex literal with static analysis.

**Comment by dfego** [comment]
I encountered this myself, when one of my coding contract solution scripts had a method (inside of a class) named `buyStock` and the static RAM checker mistook it for `stocks.buyStock`.

I was thinking about this and trying to look at the relevant code a bit, and thought: why can't this be done with equality? For example, in the following script:
```js
/** @param {NS} ns */
export async function main(ns) {
  const trickery = ns.ps;
  const trickery2 = ns;
  ns.tprintf(`${ps === ns.ps}`);
  ns.tprintf(`${trickery === ns.ps}`);
  ns.tprintf(`${trickery2.ls === ns.ls}`);
}

function ps() {}
```

It prints:
```
false
true
true
```

And `mem` shows:
```
This script requires 2.00GB of RAM to run for 1 thread(s)
  1.60GB | baseCost (misc)
  0.20GB | ps (fn)
  0.20GB | ls (fn)
  ```

That would mean it's possible to distinguish correctly which things are lib functions and which are not.

Now, it looks like the way it's being done (maybe because it has to be) is by parsing the code itself, rather than in any way loading it. That said, it the memory checker can seem to tell that a variable named `trickery` is in fact the same as `ps`, and yet gets `ps` and `ns.ps` confused. How is it doing introspection into variable assignments such that it catches that case?

**Comment by d0sboots** [comment]
You're confusing two different contexts here.

The equality checks you're doing are happening at *run-time*. Just like the dynamic RAM checker, it happens through actually running the code, not through any kind of parsing. At run-time, it is definitely possible to tell what is a lib function and what is not.

However, the **static** RAM checker is a **static** analysis, which happens *without* running the code. In other words, it happens through parsing. It needs to be this way, because of something known as the halting problem - it is impossible to know how much RAM a script will use without actually running it, but running it could take an infinite amount of time (it might never halt). Instead, the static check is an upper-bound on the RAM use, by looking for names of functions that might/probably will be called. But it isn't (and can't be) perfect.

Trying to track variable assignments across static analysis is very hard, and in the general case impossible, since they can rely on the results of conditionals, etc. - it reduces to "you have to just run the code."

**Comment by AugSphere** [comment]
> Trying to track variable assignments across static analysis is very hard, and in the general case impossible, since they can rely on the results of conditionals, etc. - it reduces to "you have to just run the code."

We should be able to parse the code into an abstract syntax tree and verity which instances of `exec` or anything else definitely belong on a netscript object and which ones might not, right? IDEs are capable of figuring out which object I just tried to autocomplete a method for correctly in basically all cases and they do it via static analysis.

**Comment by d0sboots** [comment]
We *are* parsing the code into an abstract syntax tree, that's how we can tell these are function calls at all and not just random identifiers.

Doing more is not completely impossible, just very difficult. For instance, IDEs are helped out (in the case of JS) by type annotations on functions, and they still fail many times in their control-flow analysis when conditionals are involved. But whereas it is OK for an IDE to fail low (assume no type and go with generic completion), we have to fail high (assume it *could* be `ns` and assign a static cost), because the alternative is that the script fails at runtime with a cryptic error message.

It is *much* harder to show that something can *not* be an `ns` instance, statically, than it is to know what things *are* `ns` instances. There are cases that are easy enough, like your regex literals, but they aren't the majority of the problem by far.

**Comment by AugSphere** [comment]
> It is _much_ harder to show that something can _not_ be an `ns` instance, statically, than it is to know what things _are_ `ns` instances. There are cases that are easy enough, like your regex literals, but they aren't the majority of the problem by far.

That's a fair point, yeah. I don't have the time to contribute significant general improvements to this and introducing a special case just for regex doesn't feel worth it, so I'd be fine closing the issue.
